language: java
jdk:
- oraclejdk8

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE USER pwd WITH PASSWORD 'pwd';" -U postgres
  - psql -c 'CREATE DATABASE pwd_integration OWNER pwd;' -U postgres
  - psql -c "CREATE EXTENSION unaccent;" -U postgres -d pwd_integration