language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: WqcMM3GFL4zs03avVkS12xyQChOJH1cmvASg3lxqBQNaqtUjz0TTEM4oqI2W53XkU/ihGiU6gXOlN6jDMpZbGPEQv2VBlhw3lvteygdFPPzOK6Y2TqlXJl+4CPxgcsMXFT33SO62a6OXB/axefDLYpcgKjJ6XqhXoyRTEN28u/IMu60Kc++VrGMDsUza2RH6XKdEIAK4pOWv5W1/WfAUN32uGkXA+jn+tgJYU7fHHfV/75LT290h795qVodbte4jo+8jSLTBxLCV7kB5aEH+6QNxzcU7wFPryzmM8cNEPQuKCMGKAd6W9VJ7mZ1KoNynyziu9z28n2CD+Jthur9AeRLZxncb4JUiBxczT4nWTWFVHoWPmBHpCLkFiDW5+DAmhYCm7b/yfkF9Cphy0hxpm1BZyDKL+MrhzeBZmlZsAURgN2TIKyZVSqsAsGiXf+MfmnMIzMhFlHZav6Gz9lDrgfE9vL869visp73bh5wFPfMNCpJ7VzlTQYRgUGgyN4kSxIw8hew57O+Agadkxj344aKPu8mkux+ykaxP45lX8fWfZV0vIdAyVlEh7m9ou0ocncg5xveWP84Gx6XYbPE6yEwSeAJU6vkhAURgrFuxRyaCIC9jLlOCvEBIY4BecOgr6iFF8+NN46mfeFzmoLrUzep2JNYxwFW9P4QBLtGhbAY=
  app: pwd-prod
  on: master
env:
  global:
    secure: K1UUfhL8KACEeVMGb7vporQGViiU6qzj/79sofDtOe4zFgSVniMS87Qe+A6Lr/qam+p7P/U3wzio7h1H5CaBNSRkQ4oHaIFbVy3oXOOEIE1L9NJSI/Kn9ul34QkG5LuEeXVMYaN/+YFpxwiKeUJmzMVxLeytCgmnZlnwxtWhuMAvZxRwI90uiW0g3T5I4v1xeMi3TNIY5M4nsZerZzmHqNGn7uH2s/9i7IfYtuajPKc/3idGwHJZ27oPVV0ixYF2BmuJgIIsu9yIZxvmZFUKS9yJC05GUbCpglI6NLUhrSNLaYsuvfU27yEW0fycdrFntVpHQ5sAqBqF0Gy9p9re5X/F/jG9ovCqUaHJtFdmTxN4ds5wF8OEjJ9GLQSu9KqKweT3/qz/5eQUktQwAn0IIUaRWlsK090kZ943aZdHepAvjTQ8YW/To4DGsDQyJjSMYT+VL0m/NTFrQ7Y9+EY/pAvvujnFN1vfYyWkvaMcVlXivHYQ4SYljtW/c7BX16kmu2lRt5+37rKXTklCR3w3rEAsDE0YBS8TQjazhHvDhvvwC/nTEZuQ8+eG8q3kcZ69OnzbY9SmZvFeh4iq7vn/NGO3f7p9Sd7nMEuDiKQ10q1oaBylJ7GkG4nWYQ1GU6Wu4pPhjp6czPxBsgePOcUhhbIXqfdeZOHpTxhhbS0fGKk=
