spring:
  jpa:
    database-platform: org.pwd.hibernate.JsonPostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pwd
    username: pwd
    password: pwd
    initialize: false
    continue-on-error: false

analysis:
  endpoint: https://rocky-citadel-6277.herokuapp.com/analysis

error:
  whitelabel:
    enabled: false