spring:
  jpa:
    database-platform: org.pwd.hibernate.JsonH2SQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test

server:
    port: 8081