spring:
  jpa:
    database-platform: org.pwd.hibernate.JsonPostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pwd
    username: pwd
    password: pwd
    initialize: false
    continue-on-error: false

analysis:
  endpoint: http://pwd-analysis.herokuapp.com/analysis

smtp:
  host: ????
  username: ????
  password: ????
  mailbox: kontakt@pwd.dolinagubra.pl
  port: 25

error:
  whitelabel:
    enabled: false