spring:
  jpa:
    database-platform: org.pwd.hibernate.JsonPostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pwd
    username: pwd
    password: pwd
    initialize: false
    continue-on-error: false
  http:
    encoding:
      charset: UTF-8

analysis:
  endpoint: http://pwd-analysis.herokuapp.com/analysis

mailgun:
 apikey: dummyKey
 domain: http://localhost

error:
  whitelabel:
    enabled: false

pwd:
  mailbox: pwd_kontakt@dolinagubra.pl
