spring:
  jpa:
    database-platform: org.pwd.hibernate.JsonPostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pwd
    username: pwd
    password: pwd
    initialize: false
    continue-on-error: false
  http:
    encoding:
      charset: UTF-8

analysis:
  endpoint: http://pwd-analysis.herokuapp.com/analysis

mailgun:
 apikey: api:key-7c8372668a767d2451eb619275539e1c
 domain: https://api.mailgun.net/v3/app50c0450aa2a1473b877781f0e1ab1d96.mailgun.org

error:
  whitelabel:
    enabled: false

pwd:
  mailbox: pwd_kontakt@dolinagubra.pl
