--copy website from 'd:/websites_init.csv' delimiter ';' CSV quote '"';
--select 'insert into website(id, city, county, voivodeship, administrative_unit, url) values ('||id||',"'||administrative_unit||'","'||url||'");' from  website;

INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (1,'Żabia Wola','grodziski','mazowieckie','Urząd Gminy Żabia Wola','http://www.zabiawola.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (2,'Korsze','kętrzyński','warmińsko-mazurskie','Urząd Miejski w Korszach','http://www.korsze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (3,'Sępopol','bartoszycki','warmińsko-mazurskie','Urząd Miejski w Sępopolu','http://bip.warmia.mazury.pl/sepopol_gmina_miejsko_-_wiejska');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (4,'Bartoszyce','bartoszycki','warmińsko-mazurskie','Starostwo Powiatowe w Bartoszycach','http://wrota.warmia.mazury.pl/powiat_bartoszycki');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (5,'Bartoszyce','bartoszycki','warmińsko-mazurskie','Urząd Miasta Bartoszyce','http://www.bartoszyce.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (6,'Warszawa','warszawski','mazowieckie','Urząd Marszałkowski Województwa Mazowieckiego','http://www.mazovia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (7,'Warszawa','warszawski','mazowieckie','Urząd Miasta Stołecznego Warszawy','http://www.um.warszawa.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (8,'Warszawa','warszawski','mazowieckie','Mazowiecki Urząd Wojewódzki','http://www.mazowieckie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (9,'Białobrzegi','białobrzeski','mazowieckie','Starostwo Powiatowe w Białobrzegach','http://www.bialobrzegipowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (10,'Ciechanów','ciechanowski','mazowieckie','Starostwo Powiatowe w Ciechanowie','http://www.ciechanow.powiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (11,'Garwolin','garwoliński','mazowieckie','Starostwo Powiatowe w Garwolinie','http://www.garwolin-starostwo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (12,'Gostynin','gostyniński','mazowieckie','Starostwo Powiatowe w Gostyninie','http://www.gostynin.powiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (13,'Grodzisk Mazowiecki','grodziski','mazowieckie','Starostwo Powiatowe w Grodzisku Mazowieckim','http://www.powiat-grodziski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (14,'Grójec','grójecki','mazowieckie','Starostwo Powiatowe w Grójcu','http://www.grojec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (15,'Kozienice','kozienicki','mazowieckie','Starostwo Powiatowe w Kozienicach','http://www.kozienicepowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (16,'Legionowo','legionowski','mazowieckie','Starostwo Powiatowe w Legionowie','http://www.powiat-legionowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (17,'Lipsko','lipski','mazowieckie','Starostwo Powiatowe w Lipsku','http://www.powiatlipsko.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (18,'Łosice','łosicki','mazowieckie','Starostwo Powiatowe w Łosicach','http://www.losice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (19,'Maków Mazowiecki','makowski','mazowieckie','Starostwo Powiatowe w Makowie Mazowieckim','http://www.powiat-makowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (20,'Mińsk Mazowiecki','miński ','mazowieckie','Starostwo Powiatowe w Mińsku Mazowieckim','http://www.powiatminski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (21,'Mława','mławski','mazowieckie','Starostwo Powiatowe w Mławie','http://www.powiatmlawski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (22,'Nowy Dwór Mazowiecki','nowodworski','mazowieckie','Starostwo Powiatowe w Nowym Dworze Mazowieckim','http://www.nowodworski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (23,'Ostrołęka','ostrołęcki','mazowieckie','Starostwo Powiatowe w Ostrołęce','http://www.powiatostrolecki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (24,'Ostrów Mazowiecka','ostrowski','mazowieckie','Starostwo Powiatowe w Ostrowi Mazowieckiej','http://www.powiatostrowmaz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (25,'Otwock','otwocki','mazowieckie','Starostwo Powiatowe w Otwocku','http://www.powiat-otwocki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (26,'Ożarów Mazowiecki','warszawski zachodni','mazowieckie','Starostwo Powiatowe w Ożarowie Mazowieckim','http://www.pwz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (27,'Piaseczno','piaseczyński','mazowieckie','Starostwo Powiatowe w Piasecznie','http://www.piaseczno.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (28,'Płock','płocki','mazowieckie','Starostwo Powiatowe w Płocku','http://www.powiat-plock.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (29,'Płońsk','płoński','mazowieckie','Starostwo Powiatowe w Płońsku','http://www.powiat-plonski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (30,'Pruszków','pruszkowski','mazowieckie','Starostwo Powiatowe w Pruszkowie','http://www.powiat.pruszkow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (31,'Przasnysz','przasnyski','mazowieckie','Starostwo Powiatowe w Przasnyszu','http://www.powiat-przasnysz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (32,'Przysucha','przysuski','mazowieckie','Starostwo Powiatowe w Przysusze','http://www.przysucha.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (33,'Pułtusk','pułtuski','mazowieckie','Starostwo Powiatowe w Pułtusku','http://www.starostwopultusk.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (34,'Radom','radomski','mazowieckie','Starostwo Powiatowe w Radomiu','http://www.radompowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (35,'Siedlce','siedlecki','mazowieckie','Starostwo Powiatowe w Siedlcach','http://www.powiatsiedlecki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (36,'Sierpc','sierpecki','mazowieckie','Starostwo Powiatowe w Sierpcu','http://www.powiat.sierpc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (37,'Sochaczew','sochaczewski','mazowieckie','Starostwo Powiatowe w Sochaczewie','http://www.powiat.sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (38,'Sokołów Podlaski','sokołowski','mazowieckie','Starostwo Powiatowe w Sokołowie Podlaskim','http://www.powiat-sokolowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (39,'Szydłowiec','szydłowiecki','mazowieckie','Starostwo Powiatowe w Szydłowcu','http://www.szydlowiecpowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (40,'Węgrów','węgrowski','mazowieckie','Starostwo Powiatowe w Węgrowie','http://www.powiatwegrowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (41,'Wołomin','wołomiński','mazowieckie','Starostwo Powiatowe w Wołominie','http://www.powiat-wolominski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (42,'Wyszków','wyszkowski','mazowieckie','Starostwo Powiatowe w Wyszkowie','http://www.powiat-wyszkowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (43,'Zwoleń','zwoleński','mazowieckie','Starostwo Powiatowe w Zwoleniu','http://www.zwolenpowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (44,'Żuromin','żuromiński','mazowieckie','Starostwo Powiatowe w Żurominie','http://www.zuromin-powiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (45,'Żyrardów','żyrardowski','mazowieckie','Starostwo Powiatowe w Żyrardowie','http://www.powiat-zyrardowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (46,'Andrzejewo','ostrowski','mazowieckie','Urząd Gminy Andrzejewo','http://www.andrzejewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (47,'Baboszewo','płoński','mazowieckie','Urząd Gminy Baboszewo','http://www.gminababoszewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (48,'Baranowo','ostrołęcki','mazowieckie','Urząd Gminy Baranowo','http://www.baranowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (49,'Baranów','puławski ','lubelskie','Urząd Gminy Baranów','http://www2.gmina-baranow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (50,'Belsk Duży','grójecki','mazowieckie','Urząd Gminy Belsk Duży','http://www.belskduzy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (51,'Bielany','sokołowski','mazowieckie','Urząd Gminy Bielany','http://www.gminabielany.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (52,'Bielsk','płocki','mazowieckie','Urząd Gminy Bielsk','http://www.bielsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (53,'Błędów','grójecki','mazowieckie','Urząd Gminy Błędów','http://www.bledow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (54,'Bodzanów','płocki','mazowieckie','Urząd Gminy Bodzanów','http://www.bodzanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (55,'Boguty-Pianki','ostrowski','mazowieckie','Urząd Gminy Boguty-Pianki','http://www.gmina-boguty-pianki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (56,'Borkowice','przysuski','mazowieckie','Urząd Gminy Borkowice','http://borkowice.ehost.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (57,'Borowie','garwoliński','mazowieckie','Urząd Gminy Borowie','http://www.borowie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (58,'Brańszczyk','wyszkowski','mazowieckie','Urząd Gminy Brańszczyk','http://www.branszczyk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (59,'Brochów','sochaczewski','mazowieckie','Urząd Gminy Brochów','http://www.brochow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (60,'Brudzeń Duży','płocki','mazowieckie','Urząd Gminy Brudzeń Duży','http://www.brudzen.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (61,'Brwinów','pruszkowski','mazowieckie','Urząd Gminy Brwinów','http://www.brwinow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (62,'Bulkowo','płocki','mazowieckie','Urząd Gminy Bulkowo','http://www.bulkowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (63,'Cegłów','miński','mazowieckie','Urząd Gminy Cegłów','http://www.ceglow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (64,'Celestynów','otwocki','mazowieckie','Urząd Gminy Celestynów','http://www.celestynow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (65,'Ceranów','sokołowski','mazowieckie','Urząd Gminy Ceranów','http://www.ceranow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (66,'Chlewiska','szydłowiecki','mazowieckie','Urząd Gminy Chlewiska','http://www.chlewiska.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (67,'Chotcza-Józefów','lipski','mazowieckie','Urząd Gminy Chotcza-Józefów','http://www.chotcza.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (68,'Chynów','grójecki','mazowieckie','Urząd Gminy Chynów','http://www.chynow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (69,'Ciechanów','ciechanowski','mazowieckie','Urząd Gminy Ciechanów','http://www.gminaciechanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (70,'Ciepielów','lipski','mazowieckie','Urząd Gminy Ciepielów','http://www.ciepielow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (71,'Czarnia','ostrołęcki','mazowieckie','Urząd Gminy Czarnia','http://www.czarnia.samorzady.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (72,'Czernice Borowe','przasnyski','mazowieckie','Urząd Gminy Czernice Borowe','http://www.czerniceborowe.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (73,'Czerwin','ostrołęcki','mazowieckie','Urząd Gminy Czerwin','http://www.czerwin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (74,'Czerwińsk Nad Wisłą','płoński','mazowieckie','Urząd Gminy Czerwińsk Nad Wisłą','http://www.czerwinsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (75,'Czerwonka','makowski','mazowieckie','Urząd Gminy Czerwonka','http://www.czerwonka.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (76,'Czosnów','nowodworski','mazowieckie','Urząd Gminy Czosnów','http://www.czosnow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (77,'Dąbrówka','wołomiński','mazowieckie','Urząd Gminy Dąbrówka','http://www.dabrowka.net.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (78,'Dębe Wielkie','miński','mazowieckie','Urząd Gminy Dębe Wielkie','http://www.debewielkie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (79,'Długosiodło','wyszkowski','mazowieckie','Urząd Gminy Długosiodło','http://www.dlugosiodlo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (80,'Dobre','radziejowski','kujawsko-pomorskie','Urząd Gminy Dobre','http://www.gminadobre.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (81,'Domanice','siedlecki','mazowieckie','Urząd Gminy Domanice','http://www.domanice.i-gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (82,'Dzierzążnia','płoński','mazowieckie','Urząd Gminy Dzierzążnia','http://www.dzierzaznia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (83,'Dzierzgowo','mławski','mazowieckie','Urząd Gminy Dzierzgowo','http://www.dzierzgowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (84,'Garbatka-Letnisko','kozienicki','mazowieckie','Urząd Gminy Garbatka-Letnisko','http://www.garbatkaletnisko.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (85,'Garwolin','garwoliński','mazowieckie','Urząd Gminy Garwolin','http://www.garwolin-gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (86,'Gielniów','przysuski','mazowieckie','Urząd Gminy Gielniów','http://www.bip.gielniow.akcessnet.net');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (87,'Glinojeck','ciechanowski','mazowieckie','Urząd Gminy Glinojeck','http://www.glinojeck.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (88,'Głowaczów','kozienicki','mazowieckie','Urząd Gminy Głowaczów','http://www.glowaczow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (89,'Gniewoszów','kozienicki','mazowieckie','Urząd Gminy Gniewoszów','http://www.gniewoszow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (90,'Gołymin-Ośrodek','ciechanowski','mazowieckie','Urząd Gminy Gołymin-Ośrodek','http://www.golymin-osrodek.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (91,'Gostynin','gostyniński','mazowieckie','Urząd Gminy Gostynin','http://www.gminagostynin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (92,'Goszczyn','grójecki','mazowieckie','Urząd Gminy Goszczyn','http://www.goszczyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (93,'Goworowo','ostrołęcki','mazowieckie','Urząd Gminy Goworowo','http://www.goworowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (94,'Gozdowo','sierpecki','mazowieckie','Urząd Gminy Gozdowo','http://www.gozdowo.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (95,'Górzno','brodnicki','kujawsko-pomorskie','Urząd Gminy Górzno','http://www.gorzno.ugm.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (96,'Gózd','radomski','mazowieckie','Urząd Gminy Gózd','http://www.gozd.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (97,'Grabów Nad Pilicą','kozienicki','mazowieckie','Urząd Gminy Grabów Nad Pilicą','http://www.grabow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (98,'Grębków','węgrowski','mazowieckie','Urząd Gminy Grębków','http://www.grebkow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (99,'Grudusk','ciechanowski','mazowieckie','Urząd Gminy Grudusk','http://www.grudusk.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (100,'Gzy','pułtuski','mazowieckie','Urząd Gminy Gzy','http://www.gminagzy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (101,'Huszlew','łosicki','mazowieckie','Urząd Gminy Huszlew','http://www.huszlew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (102,'Mordy','siedlecki','mazowieckie','Urząd Gminy i Miasta Mordy','http://umigmordy.bip.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (103,'Grójec','grójecki','mazowieckie','Urząd Gminy i Miasta w Grójcu','http://www.grojecmiasto.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (104,'Przysucha','przysuski','mazowieckie','Urząd Gminy i Miasta w Przysusze','http://www.przysucha.umig.gov.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (105,'Wyszogród','płocki','mazowieckie','Urząd Gminy i Miasta Wyszogród','http://www.wyszogrod.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (106,'Żuromin','żuromiński','mazowieckie','Urząd Gminy i Miasta Żuromin','http://www.zuromin.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (107,'Iłów','sochaczewski','mazowieckie','Urząd Gminy Iłów','http://www.ilow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (108,'Izabelin','warszawski zachodni','mazowieckie','Urząd Gminy Izabelin','http://www.izabelin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (109,'Jabłonna','lubelski','lubelskie','Urząd Gminy Jabłonna','http://www.jablonna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (110,'Jabłonna Lacka','sokołowski','mazowieckie','Urząd Gminy Jabłonna Lacka','http://www.jablonnalacka.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (111,'Jadów','wołomiński','mazowieckie','Urząd Gminy Jadów','http://www.jadow.az.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (112,'Jaktorów','grodziski','mazowieckie','Urząd Gminy Jaktorów','http://www.jaktorow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (113,'Jakubów','miński','mazowieckie','Urząd Gminy Jakubów','http://www.jakubow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (114,'Jasieniec','grójecki','mazowieckie','Urząd Gminy Jasieniec','http://www.jasieniec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (115,'Jastrząb','szydłowiecki','mazowieckie','Urząd Gminy Jastrząb','http://www.jastrzab.gmina.waw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (116,'Jastrzębia','radomski','mazowieckie','Urząd Gminy Jastrzębia','http://www.jastrzebia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (117,'Jedlińsk','radomski','mazowieckie','Urząd Gminy Jedlińsk','http://www.jedlinsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (118,'Jedlnia-Letnisko','radomski','mazowieckie','Urząd Gminy Jedlnia-Letnisko','http://www.jedlnia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (119,'Jednorożec','przasnyski','mazowieckie','Urząd Gminy Jednorożec','http://www.jednorozec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (120,'Joniec','płoński','mazowieckie','Urząd Gminy Joniec','http://www.ugjoniec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (121,'Kadzidło','ostrołęcki','mazowieckie','Urząd Gminy Kadzidło','http://www.kadzidlo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (122,'Kampinos','warszawski zachodni','mazowieckie','Urząd Gminy Kampinos','http://www.kampinos.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (123,'Karniewo','makowski','mazowieckie','Urząd Gminy Karniewo','http://www.karniewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (124,'Kazanów','zwoleński','mazowieckie','Urząd Gminy Kazanów','http://www.kazanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (125,'Klembów','wołomiński','mazowieckie','Urząd Gminy Klembów','http://www.klembow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (126,'Klwów','przysuski','mazowieckie','Urząd Gminy Klwów','http://www.klwow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (127,'Kołbiel','otwocki','mazowieckie','Urząd Gminy Kołbiel','http://www.kolbiel.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (128,'Korczew','siedlecki','mazowieckie','Urząd Gminy Korczew','http://www.korczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (129,'Korytnica','węgrowski','mazowieckie','Urząd Gminy Korytnica','http://www.korytnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (130,'Kotuń','siedlecki','mazowieckie','Urząd Gminy Kotuń','http://www.kotun.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (131,'Kowala','radomski','mazowieckie','Urząd Gminy Kowala','http://www.kowala.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (132,'Krasne','przasnyski','mazowieckie','Urząd Gminy Krasne','http://www.krasne.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (133,'Krasnosielc','makowski','mazowieckie','Urząd Gminy Krasnosielc','http://www.gminakrasnosielc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (134,'Krzynowłoga Mała','przasnyski','mazowieckie','Urząd Gminy Krzynowłoga Mała','http://www.krzynowlogamala.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (135,'Kuczbork-Osada','żuromiński','mazowieckie','Urząd Gminy Kuczbork-Osada','http://www.ugkuczbork.bip.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (136,'Latowicz','miński','mazowieckie','Urząd Gminy Latowicz','http://www.gmina-latowicz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (137,'Lelis','ostrołęcki','mazowieckie','Urząd Gminy Lelis','http://www.lelis.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (138,'Leoncin','nowodworski','mazowieckie','Urząd Gminy Leoncin','http://www.leoncin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (139,'Leszno','warszawski zachodni','mazowieckie','Urząd Gminy Leszno','http://www.gminaleszno.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (140,'Lesznowola','piaseczyński','mazowieckie','Urząd Gminy Lesznowola','http://www.lesznowola.waw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (141,'Lipowiec Kościelny','mławski','mazowieckie','Urząd Gminy Lipowiec Kościelny','http://www.lipowieckoscielny.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (142,'Liw','węgrowski','mazowieckie','Urząd Gminy Liw','http://www.liw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (143,'Lubowidz','żuromiński','mazowieckie','Urząd Gminy Lubowidz','http://www.uglubowidz.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (144,'Lutocin','żuromiński','mazowieckie','Urząd Gminy Lutocin','http://www.lutocin.i-gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (145,'Łaskarzew','garwoliński','mazowieckie','Urząd Gminy Łaskarzew','http://www.laskarzew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (146,'Łąck','płocki','mazowieckie','Urząd Gminy Łąck','http://www.gminalack.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (147,'Łyse','ostrołęcki','mazowieckie','Urząd Gminy Łyse','http://www.gminalyse.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (148,'Maciejowice','garwoliński','mazowieckie','Urząd Gminy Maciejowice','http://www.maciejowice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (149,'Magnuszew','kozienicki','mazowieckie','Urząd Gminy Magnuszew','http://www.magnuszew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (150,'Mała Wieś','płocki','mazowieckie','Urząd Gminy Mała Wieś','http://www.malawies.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (151,'Małkinia Górna','ostrowski','mazowieckie','Urząd Gminy Małkinia Górna','http://www.malkiniagorna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (152,'Miastków Kościelny','garwoliński','mazowieckie','Urząd Gminy Miastków Kościelny','http://www.miastkowkoscielny.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (153,'Michałowice','krakowski','małopolskie','Urząd Gminy Michałowice','http://www.michalowice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (154,'Miedzna','węgrowski','mazowieckie','Urząd Gminy Miedzna','http://gmina-miedzna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (155,'Mińsk Mazowiecki','miński','mazowieckie','Urząd Gminy Mińsk Mazowiecki','http://www.minskmazowiecki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (156,'Mirów Stary','szydłowiecki','mazowieckie','Urząd Gminy Mirów','http://www.mirow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (157,'Młodzieszyn','sochaczewski','mazowieckie','Urząd Gminy Młodzieszyn','http://www.mlodzieszyn.e-sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (158,'Młynarze','makowski','mazowieckie','Urząd Gminy Młynarze','http://mlynarze.bipgminy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (159,'Mochowo','sierpecki','mazowieckie','Urząd Gminy Mochowo','http://www.mochowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (160,'Mokobody','siedlecki','mazowieckie','Urząd Gminy Mokobody','http://www.mokobody.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (161,'Nadarzyn','pruszkowski','mazowieckie','Urząd Gminy Nadarzyn','http://www.nadarzyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (162,'Naruszewo','płoński','mazowieckie','Urząd Gminy Naruszewo','http://www.naruszewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (163,'Nieporęt','legionowski','mazowieckie','Urząd Gminy Nieporęt','http://www.nieporet.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (164,'Nowa Sucha','sochaczewski','mazowieckie','Urząd Gminy Nowa Sucha','http://www.nowasucha.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (165,'Nowe Miasto','płoński','mazowieckie','Urząd Gminy Nowe Miasto','http://www.nowemiasto.win.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (166,'Nowy Duninów','płocki','mazowieckie','Urząd Gminy Nowy Duninów','http://www.nowyduninow.info.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (167,'Nur','ostrowski','mazowieckie','Urząd Gminy Nur','http://www.gminanur.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (168,'Obryte','pułtuski','mazowieckie','Urząd Gminy Obryte','http://www.obryte.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (169,'Odrzywół','przysuski','mazowieckie','Urząd Gminy Odrzywół','http://www.odrzywol.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (170,'Ojrzeń','ciechanowski','mazowieckie','Urząd Gminy Ojrzeń','http://www.ojrzen.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (171,'Olszanka','łosicki','mazowieckie','Urząd Gminy Olszanka','http://www.olszanka.gminarp.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (172,'Olszewo-Borki','ostrołęcki','mazowieckie','Urząd Gminy Olszewo-Borki','http://www.olszewo-borki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (173,'Opinogóra Górna','ciechanowski','mazowieckie','Urząd Gminy Opinogóra Górna','http://www.opinogora.home.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (174,'Orońsko','szydłowiecki','mazowieckie','Urząd Gminy Orońsko','http://www.oronsko.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (175,'Osieck','otwocki','mazowieckie','Urząd Gminy Osieck','http://www.osieck.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (176,'Ostrów Mazowiecka','ostrowski','mazowieckie','Urząd Gminy Ostrów Mazowiecka','http://www.gminaostrowmaz.home.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (177,'Pacyna','gostyniński','mazowieckie','Urząd Gminy Pacyna','http://www.pacyna.mazowsze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (178,'Paprotnia','siedlecki','mazowieckie','Urząd Gminy Paprotnia','http://ppaprotnia.e-bip.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (179,'Parysów','garwoliński','mazowieckie','Urząd Gminy Parysów','http://www.parysow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (180,'Pionki','radomski','mazowieckie','Urząd Gminy Pionki','http://www.gmina-pionki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (181,'Platerów','łosicki','mazowieckie','Urząd Gminy Platerów','http://www.platerow.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (182,'Płoniawy-Bramura','makowski','mazowieckie','Urząd Gminy Płoniawy-Bramura','http://www.ploniawy-bramura.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (183,'Płońsk','płoński','mazowieckie','Urząd Gminy Płońsk','http://www.ugplonsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (184,'Pniewy','grójecki','mazowieckie','Urząd Gminy Pniewy','http://www.pniewy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (185,'Pokrzywnica','pułtuski','mazowieckie','Urząd Gminy Pokrzywnica','http://www.pokrzywnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (186,'Policzna','zwoleński','mazowieckie','Urząd Gminy Policzna','http://www.policzna.ugm.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (187,'Pomiechówek','nowodworski','mazowieckie','Urząd Gminy Pomiechówek','http://www.pomiechowek.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (188,'Poświętne','opoczyński','łódzkie','Urząd Gminy Poświętne','http://poswietne.bip-e.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (189,'Potworów','przysuski','mazowieckie','Urząd Gminy Potworów','http://www.potworow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (190,'Prażmów','piaseczyński','mazowieckie','Urząd Gminy Prażmów ','http://www.prazmow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (191,'Promna','białobrzeski','mazowieckie','Urząd Gminy Promna','http://www.promna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (192,'Przasnysz','przasnyski','mazowieckie','Urząd Gminy Przasnysz','http://www.przasnysz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (193,'Przesmyki','siedlecki','mazowieckie','Urząd Gminy Przesmyki','http://www.przesmyki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (194,'Przyłęk','zwoleński','mazowieckie','Urząd Gminy Przyłęk','http://www.przylek.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (195,'Przytyk','radomski','mazowieckie','Urząd Gminy Przytyk','http://www.przytyk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (196,'Puszcza Mariańska','żyrardowski','mazowieckie','Urząd Gminy Puszcza Mariańska','http://www.puszcza-marianska.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (197,'Raciąż','płoński','mazowieckie','Urząd Gminy Raciąż','http://www.gmina.raciaz.iap.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (198,'Radzanowo','płocki','mazowieckie','Urząd Gminy Radzanowo','http://www.radzanowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (199,'Radzanów','białobrzeski','mazowieckie','Urząd Gminy Radzanów','http://www.radzanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (200,'Radzanów','białobrzeski','mazowieckie','Urząd Gminy Radzanów','http://www.radzanow.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (201,'Radziejowice','żyrardowski','mazowieckie','Urząd Gminy Radziejowice','http://www.radziejowice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (202,'Raszyn','pruszkowski','mazowieckie','Urząd Gminy Raszyn','http://www.raszyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (203,'Regimin','ciechanowski','mazowieckie','Urząd Gminy Regimin','http://www.regimin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (204,'Repki','sokołowski','mazowieckie','Urząd Gminy Repki','http://www.repki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (205,'Rościszewo','sierpecki','mazowieckie','Urząd Gminy Rościszewo','http://www.rosciszewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (206,'Rusinów','przysuski','mazowieckie','Urząd Gminy Rusinów','http://www.rusinow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (207,'Rybno','sochaczewski','mazowieckie','Urząd Gminy Rybno','http://rybno.e-sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (208,'Rząśnik','wyszkowski','mazowieckie','Urząd Gminy Rząśnik','http://www.rzasnik.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (209,'Rzeczniów','lipski','mazowieckie','Urząd Gminy Rzeczniów','http://www.rzeczniow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (210,'Rzekuń','ostrołęcki','mazowieckie','Urząd Gminy Rzekuń','http://www.rzekun.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (211,'Rzewnie','makowski','mazowieckie','Urząd Gminy Rzewnie','http://rzewnie.bipgminy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (212,'Sabnie','sokołowski','mazowieckie','Urząd Gminy Sabnie','http://www.sabnie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (213,'Sadowne','węgrowski','mazowieckie','Urząd Gminy Sadowne','http://www.sadowne.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (214,'Sanniki','gostyniński','mazowieckie','Urząd Gminy Sanniki','http://www.sanniki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (215,'Sarnaki','łosicki','mazowieckie','Urząd Gminy Sarnaki','http://www.sarnaki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (216,'Sieciechów','kozienicki','mazowieckie','Urząd Gminy Sieciechów','http://www.sieciechow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (217,'Siedlce','siedlecki','mazowieckie','Urząd Gminy Siedlce','http://www.gminasiedlce.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (218,'Siemiątkowo','żuromiński','mazowieckie','Urząd Gminy Siemiątkowo','http://www.siemiatkowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (219,'Siennica','miński','mazowieckie','Urząd Gminy Siennica','http://www.ugsiennica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (220,'Sienno','lipski','mazowieckie','Urząd Gminy Sienno','http://www.sienno.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (221,'Sierpc','sierpecki','mazowieckie','Urząd Gminy Sierpc','http://www.gmina.sierpc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (222,'Skórzec','siedlecki','mazowieckie','Urząd Gminy Skórzec','http://www.gminawskorcu.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (223,'Słubice','płocki','mazowieckie','Urząd Gminy Słubice','http://www.slubice.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (224,'Słupno','płocki','mazowieckie','Urząd Gminy Słupno','http://www.slupno.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (225,'Sobienie-Jeziory','otwocki','mazowieckie','Urząd Gminy Sobienie-Jeziory','http://www.sobieniejeziory.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (226,'Sobolew','garwoliński','mazowieckie','Urząd Gminy Sobolew','http://www.sobolew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (227,'Sochaczew','sochaczewski','mazowieckie','Urząd Gminy Sochaczew','http://www.gmina.e-sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (228,'Sochocin','płoński','mazowieckie','Urząd Gminy Sochocin','http://www.sochocin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (229,'Sokołów Podlaski','sokołowski','mazowieckie','Urząd Gminy Sokołów Podlaski','http://www.gminasokolowpodl.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (230,'Solec Nad Wisłą','lipski','mazowieckie','Urząd Gminy Solec Nad Wisłą','http://www.solec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (231,'Somianka','wyszkowski','mazowieckie','Urząd Gminy Somianka','http://www.somianka.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (232,'Sońsk','ciechanowski','mazowieckie','Urząd Gminy Sońsk','http://www.sonsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (233,'Stanisławów','miński','mazowieckie','Urząd Gminy Stanisławów','http://www.stanislawow.ug.gov.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (234,'Stara Biała','płocki','mazowieckie','Urząd Gminy Stara Biała','http://www.starabiala.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (235,'Stara Błotnica','białobrzeski','mazowieckie','Urząd Gminy Stara Błotnica','http://www.starablotnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (236,'Stara Kornica','łosicki','mazowieckie','Urząd Gminy Stara Kornica','http://www.kornica.org');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (237,'Stare Babice','warszawski zachodni','mazowieckie','Urząd Gminy Stare Babice','http://www.stare-babice.waw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (238,'Staroźreby','płocki','mazowieckie','Urząd Gminy Staroźreby','http://www.starozreby.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (239,'Stary Lubotyń','ostrowski','mazowieckie','Urząd Gminy Stary Lubotyń','http://www.lubotyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (240,'Sterdyń','sokołowski','mazowieckie','Urząd Gminy Sterdyń','http://www.sterdyn.nwg.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (241,'Stoczek','węgrowski','mazowieckie','Urząd Gminy Stoczek','http://www.stoczek.net.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (242,'Strachówka','wołomiński','mazowieckie','Urząd Gminy Strachówka','http://www.strachowka.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (243,'Stromiec','białobrzeski','mazowieckie','Urząd Gminy Stromiec','http://www.ugstromiec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (244,'Strzegowo','mławski','mazowieckie','Urząd Gminy Strzegowo','http://www.strzegowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (245,'Stupsk','mławski','mazowieckie','Urząd Gminy Stupsk','http://www.stupsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (246,'Suchożebry','siedlecki','mazowieckie','Urząd Gminy Suchożebry','http://www.suchozebry.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (247,'Sypniewo','makowski','mazowieckie','Urząd Gminy Sypniewo','http://www.sypniewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (248,'Szczawin Kościelny','gostyniński','mazowieckie','Urząd Gminy Szczawin Kościelny','http://www.szczawin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (249,'Szczutowo','sierpecki','mazowieckie','Urząd Gminy Szczutowo','http://www.szczutowo.nowybip.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (250,'Stary Szelków','makowski','mazowieckie','Urząd Gminy Szelków','http://www.szelkow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (251,'Szreńsk','mławski','mazowieckie','Urząd Gminy Szreńsk','http://www.szrensk.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (252,'Szulborze Wielkie','ostrowski','mazowieckie','Urząd Gminy Szulborze Wielkie','http://www.ugszulborze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (253,'Szydłowo','mławski','mazowieckie','Urząd Gminy Szydłowo','http://szydlowo-maz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (254,'Świercze','pułtuski','mazowieckie','Urząd Gminy Świercze','http://www.swiercze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (255,'Tczów','zwoleński','mazowieckie','Urząd Gminy Tczów','http://www.tczow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (256,'Teresin','sochaczewski','mazowieckie','Urząd Gminy Teresin','http://www.teresin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (257,'Trojanów','garwoliński','mazowieckie','Urząd Gminy Trojanów','http://www.trojanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (258,'Troszyn','ostrołęcki','mazowieckie','Urząd Gminy Troszyn','http://www.troszyn.asi.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (259,'Brok','ostrowski','mazowieckie','Urząd Gminy w Broku','http://www.brok.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (260,'Różan','makowski','mazowieckie','Urząd Gminy w Różanie','http://www.rozan.eur.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (261,'Wąsewo','ostrowski','mazowieckie','Urząd Gminy Wąsewo','http://www.wasewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (262,'Wiązowna','otwocki','mazowieckie','Urząd Gminy Wiązowna','http://www.wiazowna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (263,'Wieczfnia Kościelna','mławski','mazowieckie','Urząd Gminy Wieczfnia Kościelna','http://www.bip.wieczfnia.akcessnet.net');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (264,'Wieliszew','legionowski','mazowieckie','Urząd Gminy Wieliszew','http://www.wieliszew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (265,'Wieniawa','przysuski','mazowieckie','Urząd Gminy Wieniawa','http://www.wieniawa.gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (266,'Wierzbica','chełmski','lubelskie','Urząd Gminy Wierzbica','http://www.wierzbica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (267,'Wierzbno','węgrowski','mazowieckie','Urząd Gminy Wierzbno','http://www.wierzbno.bumsoft-2.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (268,'Wilga','garwoliński','mazowieckie','Urząd Gminy Wilga','http://www.ugwilga.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (269,'Winnica','pułtuski','mazowieckie','Urząd Gminy Winnica','http://www.gminawinnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (270,'Wiskitki','żyrardowski','mazowieckie','Urząd Gminy Wiskitki','http://www.wiskitki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (271,'Wiśniew','siedlecki','mazowieckie','Urząd Gminy Wiśniew','http://www.wisniew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (272,'Wiśniewo','mławski','mazowieckie','Urząd Gminy Wiśniewo','http://www.wisniewo.bipgmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (273,'Wodynie','siedlecki','mazowieckie','Urząd Gminy Wodynie','http://www.wodynie.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (274,'Wolanów','radomski','mazowieckie','Urząd Gminy Wolanów','http://www.wolanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (275,'Zabrodzie','wyszkowski','mazowieckie','Urząd Gminy Zabrodzie','http://www.zabrodzie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (276,'Zakroczym','nowodworski','mazowieckie','Urząd Gminy Zakroczym','http://www.zakroczym.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (277,'Zakrzew','lubelski','lubelskie','Urząd Gminy Zakrzew','http://www.zakrzew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (278,'Załuski','płoński','mazowieckie','Urząd Gminy Załuski','http://www.zaluski.iap.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (279,'Zaręby Kościelne','ostrowski','mazowieckie','Urząd Gminy Zaręby Kościelne','http://www.zareby-kosc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (280,'Zatory','pułtuski','mazowieckie','Urząd Gminy Zatory','http://www.zatory.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (281,'Zawidz Kościelny','sierpecki','mazowieckie','Urząd Gminy Zawidz Kościelny','http://ug.zawidz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (282,'Zbuczyn','siedlecki','mazowieckie','Urząd Gminy Zbuczyn','http://www.zbuczyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (283,'Ciechanów','ciechanowski','mazowieckie','Urząd Miasta Ciechanów','http://www.umciechanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (284,'Garwolin','garwoliński','mazowieckie','Urząd Miasta Garwolin','http://www.garwolin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (285,'Gostynin','gostyniński','mazowieckie','Urząd Miasta Gostynin','http://www.gostynin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (286,'Lipsko','lipski','mazowieckie','Urząd Miasta i Gminy  Lipsko','http://www.lipsko.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (287,'Bieżuń','żuromiński','mazowieckie','Urząd Miasta i Gminy Bieżuń','http://www.biezun.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (288,'Gąbin','płocki','mazowieckie','Urząd Miasta i Gminy Gąbin','http://www.gabin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (289,'Góra Kalwaria','piaseczyński','mazowieckie','Urząd Miasta i Gminy Góra Kalwaria','http://www.gorakalwaria.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (290,'Kałuszyn','miński','mazowieckie','Urząd Miasta i Gminy Kałuszyn','http://www.kaluszyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (291,'Konstancin-Jeziorna','piaseczyński','mazowieckie','Urząd Miasta i Gminy Konstancin-Jeziorna','http://www.konstancinjeziorna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (292,'Kosów Lacki','sokołowski','mazowieckie','Urząd Miasta i Gminy Kosów Lacki','http://www.kosowlacki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (293,'Mrozy','miński','mazowieckie','Urząd Miasta i Gminy Mrozy','http://www.mrozy.bip.net.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (294,'Nowe Miasto nad Pilicą','grójecki','mazowieckie','Urząd Miasta i Gminy Nowe Miasto nad Pilicą','http://www.nowemiasto.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (295,'Piaseczno','piaseczyński','mazowieckie','Urząd Miasta i Gminy Piaseczno','http://www.piaseczno.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (296,'Pilawa','garwoliński','mazowieckie','Urząd Miasta i Gminy Pilawa','http://www.pilawa.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (297,'Radzymin','wołomiński','mazowieckie','Urząd Miasta i Gminy Radzymin','http://www.radzymin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (298,'Białobrzegi','białobrzeski','mazowieckie','Urząd Miasta i Gminy w Białobrzegach','http://www.bialobrzegi.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (299,'Chorzele','przasnyski','mazowieckie','Urząd Miasta i Gminy w Chorzelach','http://www.gminachorzele.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (300,'Drobin','płocki','mazowieckie','Urząd Miasta i Gminy w Drobinie','http://www.drobin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (301,'Łosice','łosicki','mazowieckie','Urząd Miasta i Gminy w Łosicach','http://www.losiceonline.republika.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (302,'Mogielnica','grójecki','mazowieckie','Urząd Miasta i Gminy w Mogielnicy','http://www.mogielnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (303,'Serock','legionowski','mazowieckie','Urząd Miasta i Gminy w Serocku','http://www.serock.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (304,'Skaryszew','radomski','mazowieckie','Urząd Miasta i Gminy w Skaryszewie','http://www.skaryszew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (305,'Żelechów','garwoliński','mazowieckie','Urząd Miasta i Gminy Żelechów','http://www.zelechow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (306,'Józefów','otwocki','mazowieckie','Urząd Miasta Józefowa','http://www.jozefow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (307,'Kobyłka','wołomiński','mazowieckie','Urząd Miasta Kobyłka','http://www.kobylka.pl');
