delete from web_site;

copy website from 'd:/websites_init.csv' delimiter ';' CSV quote '"';

select * from  web_site;

-------------------------------------------------------------------------------
select 'insert into website(id, city, county, voivodeship, administrative_unit, url) values ('||id||',"'||administrative_unit||'","'||url||'");' from  website;

INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (1,'¯abia Wola','grodziski','mazowieckie','Urz¹d Gminy ¯abia Wola','http://www.zabiawola.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (2,'Korsze','kêtrzyñski','warmiñsko-mazurskie','Urz¹d Miejski w Korszach','http://www.korsze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (3,'Sêpopol','bartoszycki','warmiñsko-mazurskie','Urz¹d Miejski w Sêpopolu','http://bip.warmia.mazury.pl/sepopol_gmina_miejsko_-_wiejska');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (4,'Bartoszyce','bartoszycki','warmiñsko-mazurskie','Starostwo Powiatowe w Bartoszycach','http://wrota.warmia.mazury.pl/powiat_bartoszycki');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (5,'Bartoszyce','bartoszycki','warmiñsko-mazurskie','Urz¹d Miasta Bartoszyce','http://www.bartoszyce.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (6,'Warszawa','warszawski','mazowieckie','Urz¹d Marsza³kowski Województwa Mazowieckiego','http://www.mazovia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (7,'Warszawa','warszawski','mazowieckie','Urz¹d Miasta Sto³ecznego Warszawy','http://www.um.warszawa.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (8,'Warszawa','warszawski','mazowieckie','Mazowiecki Urz¹d Wojewódzki','http://www.mazowieckie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (9,'Bia³obrzegi','bia³obrzeski','mazowieckie','Starostwo Powiatowe w Bia³obrzegach','http://www.bialobrzegipowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (10,'Ciechanów','ciechanowski','mazowieckie','Starostwo Powiatowe w Ciechanowie','http://www.ciechanow.powiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (11,'Garwolin','garwoliñski','mazowieckie','Starostwo Powiatowe w Garwolinie','http://www.garwolin-starostwo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (12,'Gostynin','gostyniñski','mazowieckie','Starostwo Powiatowe w Gostyninie','http://www.gostynin.powiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (13,'Grodzisk Mazowiecki','grodziski','mazowieckie','Starostwo Powiatowe w Grodzisku Mazowieckim','http://www.powiat-grodziski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (14,'Grójec','grójecki','mazowieckie','Starostwo Powiatowe w Grójcu','http://www.grojec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (15,'Kozienice','kozienicki','mazowieckie','Starostwo Powiatowe w Kozienicach','http://www.kozienicepowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (16,'Legionowo','legionowski','mazowieckie','Starostwo Powiatowe w Legionowie','http://www.powiat-legionowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (17,'Lipsko','lipski','mazowieckie','Starostwo Powiatowe w Lipsku','http://www.powiatlipsko.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (18,'£osice','³osicki','mazowieckie','Starostwo Powiatowe w £osicach','http://www.losice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (19,'Maków Mazowiecki','makowski','mazowieckie','Starostwo Powiatowe w Makowie Mazowieckim','http://www.powiat-makowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (20,'Miñsk Mazowiecki','miñski ','mazowieckie','Starostwo Powiatowe w Miñsku Mazowieckim','http://www.powiatminski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (21,'M³awa','m³awski','mazowieckie','Starostwo Powiatowe w M³awie','http://www.powiatmlawski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (22,'Nowy Dwór Mazowiecki','nowodworski','mazowieckie','Starostwo Powiatowe w Nowym Dworze Mazowieckim','http://www.nowodworski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (23,'Ostro³êka','ostro³êcki','mazowieckie','Starostwo Powiatowe w Ostro³êce','http://www.powiatostrolecki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (24,'Ostrów Mazowiecka','ostrowski','mazowieckie','Starostwo Powiatowe w Ostrowi Mazowieckiej','http://www.powiatostrowmaz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (25,'Otwock','otwocki','mazowieckie','Starostwo Powiatowe w Otwocku','http://www.powiat-otwocki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (26,'O¿arów Mazowiecki','warszawski zachodni','mazowieckie','Starostwo Powiatowe w O¿arowie Mazowieckim','http://www.pwz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (27,'Piaseczno','piaseczyñski','mazowieckie','Starostwo Powiatowe w Piasecznie','http://www.piaseczno.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (28,'P³ock','p³ocki','mazowieckie','Starostwo Powiatowe w P³ocku','http://www.powiat-plock.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (29,'P³oñsk','p³oñski','mazowieckie','Starostwo Powiatowe w P³oñsku','http://www.powiat-plonski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (30,'Pruszków','pruszkowski','mazowieckie','Starostwo Powiatowe w Pruszkowie','http://www.powiat.pruszkow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (31,'Przasnysz','przasnyski','mazowieckie','Starostwo Powiatowe w Przasnyszu','http://www.powiat-przasnysz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (32,'Przysucha','przysuski','mazowieckie','Starostwo Powiatowe w Przysusze','http://www.przysucha.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (33,'Pu³tusk','pu³tuski','mazowieckie','Starostwo Powiatowe w Pu³tusku','http://www.starostwopultusk.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (34,'Radom','radomski','mazowieckie','Starostwo Powiatowe w Radomiu','http://www.radompowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (35,'Siedlce','siedlecki','mazowieckie','Starostwo Powiatowe w Siedlcach','http://www.powiatsiedlecki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (36,'Sierpc','sierpecki','mazowieckie','Starostwo Powiatowe w Sierpcu','http://www.powiat.sierpc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (37,'Sochaczew','sochaczewski','mazowieckie','Starostwo Powiatowe w Sochaczewie','http://www.powiat.sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (38,'Soko³ów Podlaski','soko³owski','mazowieckie','Starostwo Powiatowe w Soko³owie Podlaskim','http://www.powiat-sokolowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (39,'Szyd³owiec','szyd³owiecki','mazowieckie','Starostwo Powiatowe w Szyd³owcu','http://www.szydlowiecpowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (40,'Wêgrów','wêgrowski','mazowieckie','Starostwo Powiatowe w Wêgrowie','http://www.powiatwegrowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (41,'Wo³omin','wo³omiñski','mazowieckie','Starostwo Powiatowe w Wo³ominie','http://www.powiat-wolominski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (42,'Wyszków','wyszkowski','mazowieckie','Starostwo Powiatowe w Wyszkowie','http://www.powiat-wyszkowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (43,'Zwoleñ','zwoleñski','mazowieckie','Starostwo Powiatowe w Zwoleniu','http://www.zwolenpowiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (44,'¯uromin','¿uromiñski','mazowieckie','Starostwo Powiatowe w ¯urominie','http://www.zuromin-powiat.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (45,'¯yrardów','¿yrardowski','mazowieckie','Starostwo Powiatowe w ¯yrardowie','http://www.powiat-zyrardowski.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (46,'Andrzejewo','ostrowski','mazowieckie','Urz¹d Gminy Andrzejewo','http://www.andrzejewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (47,'Baboszewo','p³oñski','mazowieckie','Urz¹d Gminy Baboszewo','http://www.gminababoszewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (48,'Baranowo','ostro³êcki','mazowieckie','Urz¹d Gminy Baranowo','http://www.baranowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (49,'Baranów','pu³awski ','lubelskie','Urz¹d Gminy Baranów','http://www2.gmina-baranow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (50,'Belsk Du¿y','grójecki','mazowieckie','Urz¹d Gminy Belsk Du¿y','http://www.belskduzy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (51,'Bielany','soko³owski','mazowieckie','Urz¹d Gminy Bielany','http://www.gminabielany.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (52,'Bielsk','p³ocki','mazowieckie','Urz¹d Gminy Bielsk','http://www.bielsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (53,'B³êdów','grójecki','mazowieckie','Urz¹d Gminy B³êdów','http://www.bledow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (54,'Bodzanów','p³ocki','mazowieckie','Urz¹d Gminy Bodzanów','http://www.bodzanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (55,'Boguty-Pianki','ostrowski','mazowieckie','Urz¹d Gminy Boguty-Pianki','http://www.gmina-boguty-pianki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (56,'Borkowice','przysuski','mazowieckie','Urz¹d Gminy Borkowice','http://borkowice.ehost.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (57,'Borowie','garwoliñski','mazowieckie','Urz¹d Gminy Borowie','http://www.borowie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (58,'Brañszczyk','wyszkowski','mazowieckie','Urz¹d Gminy Brañszczyk','http://www.branszczyk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (59,'Brochów','sochaczewski','mazowieckie','Urz¹d Gminy Brochów','http://www.brochow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (60,'Brudzeñ Du¿y','p³ocki','mazowieckie','Urz¹d Gminy Brudzeñ Du¿y','http://www.brudzen.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (61,'Brwinów','pruszkowski','mazowieckie','Urz¹d Gminy Brwinów','http://www.brwinow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (62,'Bulkowo','p³ocki','mazowieckie','Urz¹d Gminy Bulkowo','http://www.bulkowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (63,'Ceg³ów','miñski','mazowieckie','Urz¹d Gminy Ceg³ów','http://www.ceglow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (64,'Celestynów','otwocki','mazowieckie','Urz¹d Gminy Celestynów','http://www.celestynow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (65,'Ceranów','soko³owski','mazowieckie','Urz¹d Gminy Ceranów','http://www.ceranow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (66,'Chlewiska','szyd³owiecki','mazowieckie','Urz¹d Gminy Chlewiska','http://www.chlewiska.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (67,'Chotcza-Józefów','lipski','mazowieckie','Urz¹d Gminy Chotcza-Józefów','http://www.chotcza.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (68,'Chynów','grójecki','mazowieckie','Urz¹d Gminy Chynów','http://www.chynow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (69,'Ciechanów','ciechanowski','mazowieckie','Urz¹d Gminy Ciechanów','http://www.gminaciechanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (70,'Ciepielów','lipski','mazowieckie','Urz¹d Gminy Ciepielów','http://www.ciepielow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (71,'Czarnia','ostro³êcki','mazowieckie','Urz¹d Gminy Czarnia','http://www.czarnia.samorzady.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (72,'Czernice Borowe','przasnyski','mazowieckie','Urz¹d Gminy Czernice Borowe','http://www.czerniceborowe.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (73,'Czerwin','ostro³êcki','mazowieckie','Urz¹d Gminy Czerwin','http://www.czerwin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (74,'Czerwiñsk Nad Wis³¹','p³oñski','mazowieckie','Urz¹d Gminy Czerwiñsk Nad Wis³¹','http://www.czerwinsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (75,'Czerwonka','makowski','mazowieckie','Urz¹d Gminy Czerwonka','http://www.czerwonka.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (76,'Czosnów','nowodworski','mazowieckie','Urz¹d Gminy Czosnów','http://www.czosnow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (77,'D¹brówka','wo³omiñski','mazowieckie','Urz¹d Gminy D¹brówka','http://www.dabrowka.net.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (78,'Dêbe Wielkie','miñski','mazowieckie','Urz¹d Gminy Dêbe Wielkie','http://www.debewielkie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (79,'D³ugosiod³o','wyszkowski','mazowieckie','Urz¹d Gminy D³ugosiod³o','http://www.dlugosiodlo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (80,'Dobre','radziejowski','kujawsko-pomorskie','Urz¹d Gminy Dobre','http://www.gminadobre.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (81,'Domanice','siedlecki','mazowieckie','Urz¹d Gminy Domanice','http://www.domanice.i-gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (82,'Dzierz¹¿nia','p³oñski','mazowieckie','Urz¹d Gminy Dzierz¹¿nia','http://www.dzierzaznia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (83,'Dzierzgowo','m³awski','mazowieckie','Urz¹d Gminy Dzierzgowo','http://www.dzierzgowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (84,'Garbatka-Letnisko','kozienicki','mazowieckie','Urz¹d Gminy Garbatka-Letnisko','http://www.garbatkaletnisko.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (85,'Garwolin','garwoliñski','mazowieckie','Urz¹d Gminy Garwolin','http://www.garwolin-gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (86,'Gielniów','przysuski','mazowieckie','Urz¹d Gminy Gielniów','http://www.bip.gielniow.akcessnet.net');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (87,'Glinojeck','ciechanowski','mazowieckie','Urz¹d Gminy Glinojeck','http://www.glinojeck.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (88,'G³owaczów','kozienicki','mazowieckie','Urz¹d Gminy G³owaczów','http://www.glowaczow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (89,'Gniewoszów','kozienicki','mazowieckie','Urz¹d Gminy Gniewoszów','http://www.gniewoszow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (90,'Go³ymin-Oœrodek','ciechanowski','mazowieckie','Urz¹d Gminy Go³ymin-Oœrodek','http://www.golymin-osrodek.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (91,'Gostynin','gostyniñski','mazowieckie','Urz¹d Gminy Gostynin','http://www.gminagostynin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (92,'Goszczyn','grójecki','mazowieckie','Urz¹d Gminy Goszczyn','http://www.goszczyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (93,'Goworowo','ostro³êcki','mazowieckie','Urz¹d Gminy Goworowo','http://www.goworowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (94,'Gozdowo','sierpecki','mazowieckie','Urz¹d Gminy Gozdowo','http://www.gozdowo.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (95,'Górzno','brodnicki','kujawsko-pomorskie','Urz¹d Gminy Górzno','http://www.gorzno.ugm.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (96,'Gózd','radomski','mazowieckie','Urz¹d Gminy Gózd','http://www.gozd.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (97,'Grabów Nad Pilic¹','kozienicki','mazowieckie','Urz¹d Gminy Grabów Nad Pilic¹','http://www.grabow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (98,'Grêbków','wêgrowski','mazowieckie','Urz¹d Gminy Grêbków','http://www.grebkow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (99,'Grudusk','ciechanowski','mazowieckie','Urz¹d Gminy Grudusk','http://www.grudusk.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (100,'Gzy','pu³tuski','mazowieckie','Urz¹d Gminy Gzy','http://www.gminagzy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (101,'Huszlew','³osicki','mazowieckie','Urz¹d Gminy Huszlew','http://www.huszlew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (102,'Mordy','siedlecki','mazowieckie','Urz¹d Gminy i Miasta Mordy','http://umigmordy.bip.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (103,'Grójec','grójecki','mazowieckie','Urz¹d Gminy i Miasta w Grójcu','http://www.grojecmiasto.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (104,'Przysucha','przysuski','mazowieckie','Urz¹d Gminy i Miasta w Przysusze','http://www.przysucha.umig.gov.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (105,'Wyszogród','p³ocki','mazowieckie','Urz¹d Gminy i Miasta Wyszogród','http://www.wyszogrod.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (106,'¯uromin','¿uromiñski','mazowieckie','Urz¹d Gminy i Miasta ¯uromin','http://www.zuromin.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (107,'I³ów','sochaczewski','mazowieckie','Urz¹d Gminy I³ów','http://www.ilow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (108,'Izabelin','warszawski zachodni','mazowieckie','Urz¹d Gminy Izabelin','http://www.izabelin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (109,'Jab³onna','lubelski','lubelskie','Urz¹d Gminy Jab³onna','http://www.jablonna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (110,'Jab³onna Lacka','soko³owski','mazowieckie','Urz¹d Gminy Jab³onna Lacka','http://www.jablonnalacka.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (111,'Jadów','wo³omiñski','mazowieckie','Urz¹d Gminy Jadów','http://www.jadow.az.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (112,'Jaktorów','grodziski','mazowieckie','Urz¹d Gminy Jaktorów','http://www.jaktorow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (113,'Jakubów','miñski','mazowieckie','Urz¹d Gminy Jakubów','http://www.jakubow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (114,'Jasieniec','grójecki','mazowieckie','Urz¹d Gminy Jasieniec','http://www.jasieniec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (115,'Jastrz¹b','szyd³owiecki','mazowieckie','Urz¹d Gminy Jastrz¹b','http://www.jastrzab.gmina.waw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (116,'Jastrzêbia','radomski','mazowieckie','Urz¹d Gminy Jastrzêbia','http://www.jastrzebia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (117,'Jedliñsk','radomski','mazowieckie','Urz¹d Gminy Jedliñsk','http://www.jedlinsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (118,'Jedlnia-Letnisko','radomski','mazowieckie','Urz¹d Gminy Jedlnia-Letnisko','http://www.jedlnia.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (119,'Jednoro¿ec','przasnyski','mazowieckie','Urz¹d Gminy Jednoro¿ec','http://www.jednorozec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (120,'Joniec','p³oñski','mazowieckie','Urz¹d Gminy Joniec','http://www.ugjoniec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (121,'Kadzid³o','ostro³êcki','mazowieckie','Urz¹d Gminy Kadzid³o','http://www.kadzidlo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (122,'Kampinos','warszawski zachodni','mazowieckie','Urz¹d Gminy Kampinos','http://www.kampinos.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (123,'Karniewo','makowski','mazowieckie','Urz¹d Gminy Karniewo','http://www.karniewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (124,'Kazanów','zwoleñski','mazowieckie','Urz¹d Gminy Kazanów','http://www.kazanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (125,'Klembów','wo³omiñski','mazowieckie','Urz¹d Gminy Klembów','http://www.klembow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (126,'Klwów','przysuski','mazowieckie','Urz¹d Gminy Klwów','http://www.klwow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (127,'Ko³biel','otwocki','mazowieckie','Urz¹d Gminy Ko³biel','http://www.kolbiel.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (128,'Korczew','siedlecki','mazowieckie','Urz¹d Gminy Korczew','http://www.korczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (129,'Korytnica','wêgrowski','mazowieckie','Urz¹d Gminy Korytnica','http://www.korytnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (130,'Kotuñ','siedlecki','mazowieckie','Urz¹d Gminy Kotuñ','http://www.kotun.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (131,'Kowala','radomski','mazowieckie','Urz¹d Gminy Kowala','http://www.kowala.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (132,'Krasne','przasnyski','mazowieckie','Urz¹d Gminy Krasne','http://www.krasne.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (133,'Krasnosielc','makowski','mazowieckie','Urz¹d Gminy Krasnosielc','http://www.gminakrasnosielc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (134,'Krzynow³oga Ma³a','przasnyski','mazowieckie','Urz¹d Gminy Krzynow³oga Ma³a','http://www.krzynowlogamala.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (135,'Kuczbork-Osada','¿uromiñski','mazowieckie','Urz¹d Gminy Kuczbork-Osada','http://www.ugkuczbork.bip.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (136,'Latowicz','miñski','mazowieckie','Urz¹d Gminy Latowicz','http://www.gmina-latowicz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (137,'Lelis','ostro³êcki','mazowieckie','Urz¹d Gminy Lelis','http://www.lelis.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (138,'Leoncin','nowodworski','mazowieckie','Urz¹d Gminy Leoncin','http://www.leoncin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (139,'Leszno','warszawski zachodni','mazowieckie','Urz¹d Gminy Leszno','http://www.gminaleszno.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (140,'Lesznowola','piaseczyñski','mazowieckie','Urz¹d Gminy Lesznowola','http://www.lesznowola.waw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (141,'Lipowiec Koœcielny','m³awski','mazowieckie','Urz¹d Gminy Lipowiec Koœcielny','http://www.lipowieckoscielny.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (142,'Liw','wêgrowski','mazowieckie','Urz¹d Gminy Liw','http://www.liw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (143,'Lubowidz','¿uromiñski','mazowieckie','Urz¹d Gminy Lubowidz','http://www.uglubowidz.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (144,'Lutocin','¿uromiñski','mazowieckie','Urz¹d Gminy Lutocin','http://www.lutocin.i-gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (145,'£askarzew','garwoliñski','mazowieckie','Urz¹d Gminy £askarzew','http://www.laskarzew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (146,'£¹ck','p³ocki','mazowieckie','Urz¹d Gminy £¹ck','http://www.gminalack.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (147,'£yse','ostro³êcki','mazowieckie','Urz¹d Gminy £yse','http://www.gminalyse.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (148,'Maciejowice','garwoliñski','mazowieckie','Urz¹d Gminy Maciejowice','http://www.maciejowice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (149,'Magnuszew','kozienicki','mazowieckie','Urz¹d Gminy Magnuszew','http://www.magnuszew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (150,'Ma³a Wieœ','p³ocki','mazowieckie','Urz¹d Gminy Ma³a Wieœ','http://www.malawies.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (151,'Ma³kinia Górna','ostrowski','mazowieckie','Urz¹d Gminy Ma³kinia Górna','http://www.malkiniagorna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (152,'Miastków Koœcielny','garwoliñski','mazowieckie','Urz¹d Gminy Miastków Koœcielny','http://www.miastkowkoscielny.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (153,'Micha³owice','krakowski','ma³opolskie','Urz¹d Gminy Micha³owice','http://www.michalowice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (154,'Miedzna','wêgrowski','mazowieckie','Urz¹d Gminy Miedzna','http://gmina-miedzna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (155,'Miñsk Mazowiecki','miñski','mazowieckie','Urz¹d Gminy Miñsk Mazowiecki','http://www.minskmazowiecki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (156,'Mirów Stary','szyd³owiecki','mazowieckie','Urz¹d Gminy Mirów','http://www.mirow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (157,'M³odzieszyn','sochaczewski','mazowieckie','Urz¹d Gminy M³odzieszyn','http://www.mlodzieszyn.e-sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (158,'M³ynarze','makowski','mazowieckie','Urz¹d Gminy M³ynarze','http://mlynarze.bipgminy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (159,'Mochowo','sierpecki','mazowieckie','Urz¹d Gminy Mochowo','http://www.mochowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (160,'Mokobody','siedlecki','mazowieckie','Urz¹d Gminy Mokobody','http://www.mokobody.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (161,'Nadarzyn','pruszkowski','mazowieckie','Urz¹d Gminy Nadarzyn','http://www.nadarzyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (162,'Naruszewo','p³oñski','mazowieckie','Urz¹d Gminy Naruszewo','http://www.naruszewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (163,'Nieporêt','legionowski','mazowieckie','Urz¹d Gminy Nieporêt','http://www.nieporet.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (164,'Nowa Sucha','sochaczewski','mazowieckie','Urz¹d Gminy Nowa Sucha','http://www.nowasucha.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (165,'Nowe Miasto','p³oñski','mazowieckie','Urz¹d Gminy Nowe Miasto','http://www.nowemiasto.win.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (166,'Nowy Duninów','p³ocki','mazowieckie','Urz¹d Gminy Nowy Duninów','http://www.nowyduninow.info.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (167,'Nur','ostrowski','mazowieckie','Urz¹d Gminy Nur','http://www.gminanur.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (168,'Obryte','pu³tuski','mazowieckie','Urz¹d Gminy Obryte','http://www.obryte.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (169,'Odrzywó³','przysuski','mazowieckie','Urz¹d Gminy Odrzywó³','http://www.odrzywol.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (170,'Ojrzeñ','ciechanowski','mazowieckie','Urz¹d Gminy Ojrzeñ','http://www.ojrzen.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (171,'Olszanka','³osicki','mazowieckie','Urz¹d Gminy Olszanka','http://www.olszanka.gminarp.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (172,'Olszewo-Borki','ostro³êcki','mazowieckie','Urz¹d Gminy Olszewo-Borki','http://www.olszewo-borki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (173,'Opinogóra Górna','ciechanowski','mazowieckie','Urz¹d Gminy Opinogóra Górna','http://www.opinogora.home.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (174,'Oroñsko','szyd³owiecki','mazowieckie','Urz¹d Gminy Oroñsko','http://www.oronsko.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (175,'Osieck','otwocki','mazowieckie','Urz¹d Gminy Osieck','http://www.osieck.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (176,'Ostrów Mazowiecka','ostrowski','mazowieckie','Urz¹d Gminy Ostrów Mazowiecka','http://www.gminaostrowmaz.home.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (177,'Pacyna','gostyniñski','mazowieckie','Urz¹d Gminy Pacyna','http://www.pacyna.mazowsze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (178,'Paprotnia','siedlecki','mazowieckie','Urz¹d Gminy Paprotnia','http://ppaprotnia.e-bip.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (179,'Parysów','garwoliñski','mazowieckie','Urz¹d Gminy Parysów','http://www.parysow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (180,'Pionki','radomski','mazowieckie','Urz¹d Gminy Pionki','http://www.gmina-pionki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (181,'Platerów','³osicki','mazowieckie','Urz¹d Gminy Platerów','http://www.platerow.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (182,'P³oniawy-Bramura','makowski','mazowieckie','Urz¹d Gminy P³oniawy-Bramura','http://www.ploniawy-bramura.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (183,'P³oñsk','p³oñski','mazowieckie','Urz¹d Gminy P³oñsk','http://www.ugplonsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (184,'Pniewy','grójecki','mazowieckie','Urz¹d Gminy Pniewy','http://www.pniewy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (185,'Pokrzywnica','pu³tuski','mazowieckie','Urz¹d Gminy Pokrzywnica','http://www.pokrzywnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (186,'Policzna','zwoleñski','mazowieckie','Urz¹d Gminy Policzna','http://www.policzna.ugm.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (187,'Pomiechówek','nowodworski','mazowieckie','Urz¹d Gminy Pomiechówek','http://www.pomiechowek.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (188,'Poœwiêtne','opoczyñski','³ódzkie','Urz¹d Gminy Poœwiêtne','http://poswietne.bip-e.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (189,'Potworów','przysuski','mazowieckie','Urz¹d Gminy Potworów','http://www.potworow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (190,'Pra¿mów','piaseczyñski','mazowieckie','Urz¹d Gminy Pra¿mów ','http://www.prazmow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (191,'Promna','bia³obrzeski','mazowieckie','Urz¹d Gminy Promna','http://www.promna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (192,'Przasnysz','przasnyski','mazowieckie','Urz¹d Gminy Przasnysz','http://www.przasnysz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (193,'Przesmyki','siedlecki','mazowieckie','Urz¹d Gminy Przesmyki','http://www.przesmyki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (194,'Przy³êk','zwoleñski','mazowieckie','Urz¹d Gminy Przy³êk','http://www.przylek.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (195,'Przytyk','radomski','mazowieckie','Urz¹d Gminy Przytyk','http://www.przytyk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (196,'Puszcza Mariañska','¿yrardowski','mazowieckie','Urz¹d Gminy Puszcza Mariañska','http://www.puszcza-marianska.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (197,'Raci¹¿','p³oñski','mazowieckie','Urz¹d Gminy Raci¹¿','http://www.gmina.raciaz.iap.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (198,'Radzanowo','p³ocki','mazowieckie','Urz¹d Gminy Radzanowo','http://www.radzanowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (199,'Radzanów','bia³obrzeski','mazowieckie','Urz¹d Gminy Radzanów','http://www.radzanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (200,'Radzanów','bia³obrzeski','mazowieckie','Urz¹d Gminy Radzanów','http://www.radzanow.com');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (201,'Radziejowice','¿yrardowski','mazowieckie','Urz¹d Gminy Radziejowice','http://www.radziejowice.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (202,'Raszyn','pruszkowski','mazowieckie','Urz¹d Gminy Raszyn','http://www.raszyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (203,'Regimin','ciechanowski','mazowieckie','Urz¹d Gminy Regimin','http://www.regimin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (204,'Repki','soko³owski','mazowieckie','Urz¹d Gminy Repki','http://www.repki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (205,'Roœciszewo','sierpecki','mazowieckie','Urz¹d Gminy Roœciszewo','http://www.rosciszewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (206,'Rusinów','przysuski','mazowieckie','Urz¹d Gminy Rusinów','http://www.rusinow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (207,'Rybno','sochaczewski','mazowieckie','Urz¹d Gminy Rybno','http://rybno.e-sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (208,'Rz¹œnik','wyszkowski','mazowieckie','Urz¹d Gminy Rz¹œnik','http://www.rzasnik.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (209,'Rzeczniów','lipski','mazowieckie','Urz¹d Gminy Rzeczniów','http://www.rzeczniow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (210,'Rzekuñ','ostro³êcki','mazowieckie','Urz¹d Gminy Rzekuñ','http://www.rzekun.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (211,'Rzewnie','makowski','mazowieckie','Urz¹d Gminy Rzewnie','http://rzewnie.bipgminy.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (212,'Sabnie','soko³owski','mazowieckie','Urz¹d Gminy Sabnie','http://www.sabnie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (213,'Sadowne','wêgrowski','mazowieckie','Urz¹d Gminy Sadowne','http://www.sadowne.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (214,'Sanniki','gostyniñski','mazowieckie','Urz¹d Gminy Sanniki','http://www.sanniki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (215,'Sarnaki','³osicki','mazowieckie','Urz¹d Gminy Sarnaki','http://www.sarnaki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (216,'Sieciechów','kozienicki','mazowieckie','Urz¹d Gminy Sieciechów','http://www.sieciechow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (217,'Siedlce','siedlecki','mazowieckie','Urz¹d Gminy Siedlce','http://www.gminasiedlce.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (218,'Siemi¹tkowo','¿uromiñski','mazowieckie','Urz¹d Gminy Siemi¹tkowo','http://www.siemiatkowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (219,'Siennica','miñski','mazowieckie','Urz¹d Gminy Siennica','http://www.ugsiennica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (220,'Sienno','lipski','mazowieckie','Urz¹d Gminy Sienno','http://www.sienno.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (221,'Sierpc','sierpecki','mazowieckie','Urz¹d Gminy Sierpc','http://www.gmina.sierpc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (222,'Skórzec','siedlecki','mazowieckie','Urz¹d Gminy Skórzec','http://www.gminawskorcu.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (223,'S³ubice','p³ocki','mazowieckie','Urz¹d Gminy S³ubice','http://www.slubice.org.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (224,'S³upno','p³ocki','mazowieckie','Urz¹d Gminy S³upno','http://www.slupno.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (225,'Sobienie-Jeziory','otwocki','mazowieckie','Urz¹d Gminy Sobienie-Jeziory','http://www.sobieniejeziory.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (226,'Sobolew','garwoliñski','mazowieckie','Urz¹d Gminy Sobolew','http://www.sobolew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (227,'Sochaczew','sochaczewski','mazowieckie','Urz¹d Gminy Sochaczew','http://www.gmina.e-sochaczew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (228,'Sochocin','p³oñski','mazowieckie','Urz¹d Gminy Sochocin','http://www.sochocin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (229,'Soko³ów Podlaski','soko³owski','mazowieckie','Urz¹d Gminy Soko³ów Podlaski','http://www.gminasokolowpodl.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (230,'Solec Nad Wis³¹','lipski','mazowieckie','Urz¹d Gminy Solec Nad Wis³¹','http://www.solec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (231,'Somianka','wyszkowski','mazowieckie','Urz¹d Gminy Somianka','http://www.somianka.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (232,'Soñsk','ciechanowski','mazowieckie','Urz¹d Gminy Soñsk','http://www.sonsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (233,'Stanis³awów','miñski','mazowieckie','Urz¹d Gminy Stanis³awów','http://www.stanislawow.ug.gov.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (234,'Stara Bia³a','p³ocki','mazowieckie','Urz¹d Gminy Stara Bia³a','http://www.starabiala.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (235,'Stara B³otnica','bia³obrzeski','mazowieckie','Urz¹d Gminy Stara B³otnica','http://www.starablotnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (236,'Stara Kornica','³osicki','mazowieckie','Urz¹d Gminy Stara Kornica','http://www.kornica.org');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (237,'Stare Babice','warszawski zachodni','mazowieckie','Urz¹d Gminy Stare Babice','http://www.stare-babice.waw.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (238,'StaroŸreby','p³ocki','mazowieckie','Urz¹d Gminy StaroŸreby','http://www.starozreby.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (239,'Stary Lubotyñ','ostrowski','mazowieckie','Urz¹d Gminy Stary Lubotyñ','http://www.lubotyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (240,'Sterdyñ','soko³owski','mazowieckie','Urz¹d Gminy Sterdyñ','http://www.sterdyn.nwg.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (241,'Stoczek','wêgrowski','mazowieckie','Urz¹d Gminy Stoczek','http://www.stoczek.net.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (242,'Strachówka','wo³omiñski','mazowieckie','Urz¹d Gminy Strachówka','http://www.strachowka.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (243,'Stromiec','bia³obrzeski','mazowieckie','Urz¹d Gminy Stromiec','http://www.ugstromiec.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (244,'Strzegowo','m³awski','mazowieckie','Urz¹d Gminy Strzegowo','http://www.strzegowo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (245,'Stupsk','m³awski','mazowieckie','Urz¹d Gminy Stupsk','http://www.stupsk.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (246,'Sucho¿ebry','siedlecki','mazowieckie','Urz¹d Gminy Sucho¿ebry','http://www.suchozebry.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (247,'Sypniewo','makowski','mazowieckie','Urz¹d Gminy Sypniewo','http://www.sypniewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (248,'Szczawin Koœcielny','gostyniñski','mazowieckie','Urz¹d Gminy Szczawin Koœcielny','http://www.szczawin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (249,'Szczutowo','sierpecki','mazowieckie','Urz¹d Gminy Szczutowo','http://www.szczutowo.nowybip.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (250,'Stary Szelków','makowski','mazowieckie','Urz¹d Gminy Szelków','http://www.szelkow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (251,'Szreñsk','m³awski','mazowieckie','Urz¹d Gminy Szreñsk','http://www.szrensk.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (252,'Szulborze Wielkie','ostrowski','mazowieckie','Urz¹d Gminy Szulborze Wielkie','http://www.ugszulborze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (253,'Szyd³owo','m³awski','mazowieckie','Urz¹d Gminy Szyd³owo','http://szydlowo-maz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (254,'Œwiercze','pu³tuski','mazowieckie','Urz¹d Gminy Œwiercze','http://www.swiercze.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (255,'Tczów','zwoleñski','mazowieckie','Urz¹d Gminy Tczów','http://www.tczow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (256,'Teresin','sochaczewski','mazowieckie','Urz¹d Gminy Teresin','http://www.teresin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (257,'Trojanów','garwoliñski','mazowieckie','Urz¹d Gminy Trojanów','http://www.trojanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (258,'Troszyn','ostro³êcki','mazowieckie','Urz¹d Gminy Troszyn','http://www.troszyn.asi.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (259,'Brok','ostrowski','mazowieckie','Urz¹d Gminy w Broku','http://www.brok.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (260,'Ró¿an','makowski','mazowieckie','Urz¹d Gminy w Ró¿anie','http://www.rozan.eur.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (261,'W¹sewo','ostrowski','mazowieckie','Urz¹d Gminy W¹sewo','http://www.wasewo.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (262,'Wi¹zowna','otwocki','mazowieckie','Urz¹d Gminy Wi¹zowna','http://www.wiazowna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (263,'Wieczfnia Koœcielna','m³awski','mazowieckie','Urz¹d Gminy Wieczfnia Koœcielna','http://www.bip.wieczfnia.akcessnet.net');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (264,'Wieliszew','legionowski','mazowieckie','Urz¹d Gminy Wieliszew','http://www.wieliszew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (265,'Wieniawa','przysuski','mazowieckie','Urz¹d Gminy Wieniawa','http://www.wieniawa.gmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (266,'Wierzbica','che³mski','lubelskie','Urz¹d Gminy Wierzbica','http://www.wierzbica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (267,'Wierzbno','wêgrowski','mazowieckie','Urz¹d Gminy Wierzbno','http://www.wierzbno.bumsoft-2.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (268,'Wilga','garwoliñski','mazowieckie','Urz¹d Gminy Wilga','http://www.ugwilga.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (269,'Winnica','pu³tuski','mazowieckie','Urz¹d Gminy Winnica','http://www.gminawinnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (270,'Wiskitki','¿yrardowski','mazowieckie','Urz¹d Gminy Wiskitki','http://www.wiskitki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (271,'Wiœniew','siedlecki','mazowieckie','Urz¹d Gminy Wiœniew','http://www.wisniew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (272,'Wiœniewo','m³awski','mazowieckie','Urz¹d Gminy Wiœniewo','http://www.wisniewo.bipgmina.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (273,'Wodynie','siedlecki','mazowieckie','Urz¹d Gminy Wodynie','http://www.wodynie.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (274,'Wolanów','radomski','mazowieckie','Urz¹d Gminy Wolanów','http://www.wolanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (275,'Zabrodzie','wyszkowski','mazowieckie','Urz¹d Gminy Zabrodzie','http://www.zabrodzie.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (276,'Zakroczym','nowodworski','mazowieckie','Urz¹d Gminy Zakroczym','http://www.zakroczym.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (277,'Zakrzew','lubelski','lubelskie','Urz¹d Gminy Zakrzew','http://www.zakrzew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (278,'Za³uski','p³oñski','mazowieckie','Urz¹d Gminy Za³uski','http://www.zaluski.iap.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (279,'Zarêby Koœcielne','ostrowski','mazowieckie','Urz¹d Gminy Zarêby Koœcielne','http://www.zareby-kosc.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (280,'Zatory','pu³tuski','mazowieckie','Urz¹d Gminy Zatory','http://www.zatory.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (281,'Zawidz Koœcielny','sierpecki','mazowieckie','Urz¹d Gminy Zawidz Koœcielny','http://ug.zawidz.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (282,'Zbuczyn','siedlecki','mazowieckie','Urz¹d Gminy Zbuczyn','http://www.zbuczyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (283,'Ciechanów','ciechanowski','mazowieckie','Urz¹d Miasta Ciechanów','http://www.umciechanow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (284,'Garwolin','garwoliñski','mazowieckie','Urz¹d Miasta Garwolin','http://www.garwolin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (285,'Gostynin','gostyniñski','mazowieckie','Urz¹d Miasta Gostynin','http://www.gostynin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (286,'Lipsko','lipski','mazowieckie','Urz¹d Miasta i Gminy  Lipsko','http://www.lipsko.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (287,'Bie¿uñ','¿uromiñski','mazowieckie','Urz¹d Miasta i Gminy Bie¿uñ','http://www.biezun.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (288,'G¹bin','p³ocki','mazowieckie','Urz¹d Miasta i Gminy G¹bin','http://www.gabin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (289,'Góra Kalwaria','piaseczyñski','mazowieckie','Urz¹d Miasta i Gminy Góra Kalwaria','http://www.gorakalwaria.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (290,'Ka³uszyn','miñski','mazowieckie','Urz¹d Miasta i Gminy Ka³uszyn','http://www.kaluszyn.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (291,'Konstancin-Jeziorna','piaseczyñski','mazowieckie','Urz¹d Miasta i Gminy Konstancin-Jeziorna','http://www.konstancinjeziorna.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (292,'Kosów Lacki','soko³owski','mazowieckie','Urz¹d Miasta i Gminy Kosów Lacki','http://www.kosowlacki.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (293,'Mrozy','miñski','mazowieckie','Urz¹d Miasta i Gminy Mrozy','http://www.mrozy.bip.net.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (294,'Nowe Miasto nad Pilic¹','grójecki','mazowieckie','Urz¹d Miasta i Gminy Nowe Miasto nad Pilic¹','http://www.nowemiasto.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (295,'Piaseczno','piaseczyñski','mazowieckie','Urz¹d Miasta i Gminy Piaseczno','http://www.piaseczno.eu');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (296,'Pilawa','garwoliñski','mazowieckie','Urz¹d Miasta i Gminy Pilawa','http://www.pilawa.com.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (297,'Radzymin','wo³omiñski','mazowieckie','Urz¹d Miasta i Gminy Radzymin','http://www.radzymin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (298,'Bia³obrzegi','bia³obrzeski','mazowieckie','Urz¹d Miasta i Gminy w Bia³obrzegach','http://www.bialobrzegi.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (299,'Chorzele','przasnyski','mazowieckie','Urz¹d Miasta i Gminy w Chorzelach','http://www.gminachorzele.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (300,'Drobin','p³ocki','mazowieckie','Urz¹d Miasta i Gminy w Drobinie','http://www.drobin.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (301,'£osice','³osicki','mazowieckie','Urz¹d Miasta i Gminy w £osicach','http://www.losiceonline.republika.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (302,'Mogielnica','grójecki','mazowieckie','Urz¹d Miasta i Gminy w Mogielnicy','http://www.mogielnica.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (303,'Serock','legionowski','mazowieckie','Urz¹d Miasta i Gminy w Serocku','http://www.serock.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (304,'Skaryszew','radomski','mazowieckie','Urz¹d Miasta i Gminy w Skaryszewie','http://www.skaryszew.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (305,'¯elechów','garwoliñski','mazowieckie','Urz¹d Miasta i Gminy ¯elechów','http://www.zelechow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (306,'Józefów','otwocki','mazowieckie','Urz¹d Miasta Józefowa','http://www.jozefow.pl');
INSERT INTO website (id, city, county, voivodeship, administrative_unit, url) VALUES (307,'Koby³ka','wo³omiñski','mazowieckie','Urz¹d Miasta Koby³ka','http://www.kobylka.pl');
