--copy website from 'd:/websites_init.csv' delimiter ';' CSV quote '"';
--select 'insert into website(id, city, county, voivodeship, administrative_unit, url) values ('||id||',"'||administrative_unit||'","'||url||'");' from  website;

INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (7,1400001,'Warszawa','warszawski','mazowieckie','Mazowiecki Urząd Wojewódzki','www.mazowieckie.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (18,1401000,'Białobrzegi','białobrzeski','mazowieckie','Starostwo Powiatowe w Białobrzegach','www.bialobrzegipowiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (42,1402000,'Ciechanów','ciechanowski','mazowieckie','Starostwo Powiatowe w Ciechanowie','www.ciechanow.powiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (54,1403000,'Garwolin','garwoliński','mazowieckie','Starostwo Powiatowe w Garwolinie','www.garwolin-starostwo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (65,1404000,'Gostynin','gostyniński','mazowieckie','Starostwo Powiatowe w Gostyninie','www.gostynin.powiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (69,1405000,'Grodzisk Mazowiecki','grodziski','mazowieckie','Starostwo Powiatowe w Grodzisku Mazowieckim','www.powiat-grodziski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (71,1406000,'Grójec','grójecki','mazowieckie','Starostwo Powiatowe w Grójcu','www.grojec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (107,1407000,'Kozienice','kozienicki','mazowieckie','Starostwo Powiatowe w Kozienicach','www.kozienicepowiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (117,1408000,'Legionowo','legionowski','mazowieckie','Starostwo Powiatowe w Legionowie','www.powiat-legionowski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (126,1409000,'Lipsko','lipski','mazowieckie','Starostwo Powiatowe w Lipsku','www.powiatlipsko.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (141,1410000,'Łosice','łosicki','mazowieckie','Starostwo Powiatowe w Łosicach','www.losice.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (144,1411000,'Maków Mazowiecki','makowski','mazowieckie','Starostwo Powiatowe w Makowie Mazowieckim','www.powiat-makowski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (152,1412000,'Mińsk Mazowiecki','miński','mazowieckie','Starostwo Powiatowe w Mińsku Mazowieckim','www.powiatminski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (153,1413000,'Mława','mławski','mazowieckie','Starostwo Powiatowe w Mławie','www.powiatmlawski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (166,1414000,'Nowy Dwór Mazowiecki','nowodworski','mazowieckie','Starostwo Powiatowe w Nowym Dworze Mazowieckim','www.nowodworski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (183,1415000,'Ostrołęka','ostrołęcki','mazowieckie','Starostwo Powiatowe w Ostrołęce','www.powiatostrolecki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (185,1416000,'Ostrów Mazowiecka','ostrowski','mazowieckie','Starostwo Powiatowe w Ostrowi Mazowieckiej','www.powiatostrowmaz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (190,1417000,'Otwock','otwocki','mazowieckie','Starostwo Powiatowe w Otwocku','www.powiat-otwocki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (191,1432000,'Ożarów Mazowiecki','warszawski zachodni','mazowieckie','Starostwo Powiatowe w Ożarowie Mazowieckim','www.pwz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (195,1418000,'Piaseczno','piaseczyński','mazowieckie','Starostwo Powiatowe w Piasecznie','www.piaseczno.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (201,1419000,'Płock','płocki','mazowieckie','Starostwo Powiatowe w Płocku','www.powiat-plock.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (202,1420000,'Płońsk','płoński','mazowieckie','Starostwo Powiatowe w Płońsku','www.powiat-plonski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (210,1421000,'Pruszków','pruszkowski','mazowieckie','Starostwo Powiatowe w Pruszkowie','www.powiat.pruszkow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (211,1422000,'Przasnysz','przasnyski','mazowieckie','Starostwo Powiatowe w Przasnyszu','www.powiat-przasnysz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (214,1423000,'Przysucha','przysuski','mazowieckie','Starostwo Powiatowe w Przysusze','www.przysucha.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (218,1424000,'Pułtusk','pułtuski','mazowieckie','Starostwo Powiatowe w Pułtusku','www.starostwopultusk.org.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (221,1425000,'Radom','radomski','mazowieckie','Starostwo Powiatowe w Radomiu','www.radompowiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (236,1426000,'Siedlce','siedlecki','mazowieckie','Starostwo Powiatowe w Siedlcach','www.powiatsiedlecki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (239,1427000,'Sierpc','sierpecki','mazowieckie','Starostwo Powiatowe w Sierpcu','www.powiat.sierpc.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (246,1428000,'Sochaczew','sochaczewski','mazowieckie','Starostwo Powiatowe w Sochaczewie','www.powiat.sochaczew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (247,1429000,'Sokołów Podlaski','sokołowski','mazowieckie','Starostwo Powiatowe w Sokołowie Podlaskim','www.powiat-sokolowski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (265,1430000,'Szydłowiec','szydłowiecki','mazowieckie','Starostwo Powiatowe w Szydłowcu','www.szydlowiecpowiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (292,1433000,'Węgrów','węgrowski','mazowieckie','Starostwo Powiatowe w Węgrowie','www.powiatwegrowski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (298,1434000,'Wołomin','wołomiński','mazowieckie','Starostwo Powiatowe w Wołominie','www.powiat-wolominski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (301,1435000,'Wyszków','wyszkowski','mazowieckie','Starostwo Powiatowe w Wyszkowie','www.powiat-wyszkowski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (313,1436000,'Zwoleń','zwoleński','mazowieckie','Starostwo Powiatowe w Zwoleniu','www.zwolenpowiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (317,1437000,'Żuromin','żuromiński','mazowieckie','Starostwo Powiatowe w Żurominie','www.zuromin-powiat.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (318,1438000,'Żyrardów','żyrardowski','mazowieckie','Starostwo Powiatowe w Żyrardowie','www.powiat-zyrardowski.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (336,1416022,'Andrzejewo','ostrowski','mazowieckie','Urząd Gminy Andrzejewo','www.andrzejewo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (340,1420032,'Baboszewo','płoński','mazowieckie','Urząd Gminy Baboszewo','www.gminababoszewo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (347,1415012,'Baranowo','ostrołęcki','mazowieckie','Urząd Gminy Baranowo','www.baranowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (349,1405032,'Baranów','grodziski','mazowieckie','Urząd Gminy Baranów','www2.gmina-baranow.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (360,1406012,'Belsk Duży','grójecki','mazowieckie','Urząd Gminy Belsk Duży','www.belskduzy.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (377,1429022,'Bielany','sokołowski','mazowieckie','Urząd Gminy Bielany','www.gminabielany.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (381,1419012,'Bielsk','płocki','mazowieckie','Urząd Gminy Bielsk','www.bielsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (392,1406022,'Błędów','grójecki','mazowieckie','Urząd Gminy Błędów','www.bledow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (400,1419022,'Bodzanów','płocki','mazowieckie','Urząd Gminy Bodzanów','www.bodzanow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (404,1416032,'Boguty-Pianki','ostrowski','mazowieckie','Urząd Gminy Boguty-Pianki','www.gmina-boguty-pianki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (415,1423012,'Borkowice','przysuski','mazowieckie','Urząd Gminy Borkowice','borkowice.ehost.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (418,1403032,'Borowie','garwoliński','mazowieckie','Urząd Gminy Borowie','www.borowie.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (427,1435012,'Brańszczyk','wyszkowski','mazowieckie','Urząd Gminy Brańszczyk','www.branszczyk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (430,1428022,'Brochów','sochaczewski','mazowieckie','Urząd Gminy Brochów','www.brochow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (436,1419032,'Brudzeń Duży','płocki','mazowieckie','Urząd Gminy Brudzeń Duży','www.brudzen.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (438,1421033,'Brwinów','pruszkowski','mazowieckie','Urząd Gminy Brwinów','www.brwinow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (457,1419042,'Bulkowo','płocki','mazowieckie','Urząd Gminy Bulkowo','www.bulkowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (463,1412042,'Cegłów','miński','mazowieckie','Urząd Gminy Cegłów','www.ceglow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (466,1417032,'Celestynów','otwocki','mazowieckie','Urząd Gminy Celestynów','www.celestynow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (467,1429032,'Ceranów','sokołowski','mazowieckie','Urząd Gminy Ceranów','www.ceranow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (476,1430012,'Chlewiska','szydłowiecki','mazowieckie','Urząd Gminy Chlewiska','www.chlewiska.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (489,1409012,'Chotcza-Józefów','lipski','mazowieckie','Urząd Gminy Chotcza-Józefów','www.chotcza.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (495,1406032,'Chynów','grójecki','mazowieckie','Urząd Gminy Chynów','www.chynow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (497,1402022,'Ciechanów','ciechanowski','mazowieckie','Urząd Gminy Ciechanów','www.gminaciechanow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (500,1409022,'Ciepielów','lipski','mazowieckie','Urząd Gminy Ciepielów','www.ciepielow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (513,1415022,'Czarnia','ostrołęcki','mazowieckie','Urząd Gminy Czarnia','www.czarnia.samorzady.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (526,1422032,'Czernice Borowe','przasnyski','mazowieckie','Urząd Gminy Czernice Borowe','www.czerniceborowe.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (531,1415032,'Czerwin','ostrołęcki','mazowieckie','Urząd Gminy Czerwin','www.czerwin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (532,1420042,'Czerwińsk Nad Wisłą','płoński','mazowieckie','Urząd Gminy Czerwińsk Nad Wisłą','www.czerwinsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (534,1411022,'Czerwonka','makowski','mazowieckie','Urząd Gminy Czerwonka','www.czerwonka.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (537,1414022,'Czosnów','nowodworski','mazowieckie','Urząd Gminy Czosnów','www.czosnow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (552,1434052,'Dąbrówka','wołomiński','mazowieckie','Urząd Gminy Dąbrówka','www.dabrowka.net.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (555,1412052,'Dębe Wielkie','miński','mazowieckie','Urząd Gminy Dębe Wielkie','www.debewielkie.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (564,1435022,'Długosiodło','wyszkowski','mazowieckie','Urząd Gminy Długosiodło','www.dlugosiodlo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (571,1412062,'Dobre','miński','mazowieckie','Urząd Gminy Dobre','www.gminadobre.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (580,1426012,'Domanice','siedlecki','mazowieckie','Urząd Gminy Domanice','www.domanice.i-gmina.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (609,1420052,'Dzierzążnia','płoński','mazowieckie','Urząd Gminy Dzierzążnia','www.dzierzaznia.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (610,1413022,'Dzierzgowo','mławski','mazowieckie','Urząd Gminy Dzierzgowo','www.dzierzgowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (627,1407012,'Garbatka-Letnisko','kozienicki','mazowieckie','Urząd Gminy Garbatka-Letnisko','www.garbatkaletnisko.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (630,1403042,'Garwolin','garwoliński','mazowieckie','Urząd Gminy Garwolin','www.garwolin-gmina.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (638,1423022,'Gielniów','przysuski','mazowieckie','Urząd Gminy Gielniów','www.bip.gielniow.akcessnet.net');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (644,1402033,'Glinojeck','ciechanowski','mazowieckie','Urząd Gminy Glinojeck','www.glinojeck.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (646,1407022,'Głowaczów','kozienicki','mazowieckie','Urząd Gminy Głowaczów','www.glowaczow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (652,1407032,'Gniewoszów','kozienicki','mazowieckie','Urząd Gminy Gniewoszów','www.gniewoszow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (666,1402042,'Gołymin-Ośrodek','ciechanowski','mazowieckie','Urząd Gminy Gołymin-Ośrodek','www.golymin-osrodek.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (675,1404022,'Gostynin','gostyniński','mazowieckie','Urząd Gminy Gostynin','www.gminagostynin.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (677,1406042,'Goszczyn','grójecki','mazowieckie','Urząd Gminy Goszczyn','www.goszczyn.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (680,1415042,'Goworowo','ostrołęcki','mazowieckie','Urząd Gminy Goworowo','www.goworowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (681,1427022,'Gozdowo','sierpecki','mazowieckie','Urząd Gminy Gozdowo','www.gozdowo.eu/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (686,1403052,'Górzno','garwoliński','mazowieckie','Urząd Gminy Górzno','www.gorzno.ugm.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (688,1425022,'Gózd','radomski','mazowieckie','Urząd Gminy Gózd','www.gozd.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (693,1407042,'Grabów Nad Pilicą','kozienicki','mazowieckie','Urząd Gminy Grabów Nad Pilicą','www.grabow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (696,1433022,'Grębków','węgrowski','mazowieckie','Urząd Gminy Grębków','www.grebkow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (709,1402052,'Grudusk','ciechanowski','mazowieckie','Urząd Gminy Grudusk','www.grudusk.com');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (717,1424012,'Gzy','pułtuski','mazowieckie','Urząd Gminy Gzy','www.gminagzy.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (728,1410012,'Huszlew','łosicki','mazowieckie','Urząd Gminy Huszlew','www.huszlew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (740,1426053,'Mordy','siedlecki','mazowieckie','Urząd Gminy i Miasta Mordy','umigmordy.bip.org.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (754,1406053,'Grójec','grójecki','mazowieckie','Urząd Gminy i Miasta w Grójcu','www.grojecmiasto.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (758,1423063,'Przysucha','przysuski','mazowieckie','Urząd Gminy i Miasta w Przysusze','www.przysucha.umig.gov.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (768,1419153,'Wyszogród','płocki','mazowieckie','Urząd Gminy i Miasta Wyszogród','www.wyszogrod.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (769,1437063,'Żuromin','żuromiński','mazowieckie','Urząd Gminy i Miasta Żuromin','www.zuromin.com/news.php');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (774,1428032,'Iłów','sochaczewski','mazowieckie','Urząd Gminy Iłów','www.ilow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (784,1432022,'Izabelin','warszawski zachodni','mazowieckie','Urząd Gminy Izabelin','www.izabelin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (789,1408022,'Jabłonna','legionowski','mazowieckie','Urząd Gminy Jabłonna','www.jablonna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (790,1429042,'Jabłonna Lacka','sokołowski','mazowieckie','Urząd Gminy Jabłonna Lacka','www.jablonnalacka.com.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (792,1434062,'Jadów','wołomiński','mazowieckie','Urząd Gminy Jadów','www.jadow.az.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (793,1405052,'Jaktorów','grodziski','mazowieckie','Urząd Gminy Jaktorów','www.jaktorow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (794,1412082,'Jakubów','miński','mazowieckie','Urząd Gminy Jakubów','www.jakubow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (808,1406062,'Jasieniec','grójecki','mazowieckie','Urząd Gminy Jasieniec','www.jasieniec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (812,1430022,'Jastrząb','szydłowiecki','mazowieckie','Urząd Gminy Jastrząb','www.jastrzab.gmina.waw.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (813,1425042,'Jastrzębia','radomski','mazowieckie','Urząd Gminy Jastrzębia','www.jastrzebia.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (819,1425052,'Jedlińsk','radomski','mazowieckie','Urząd Gminy Jedlińsk','www.jedlinsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (820,1425062,'Jedlnia-Letnisko','radomski','mazowieckie','Urząd Gminy Jedlnia-Letnisko','www.jedlnia.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (821,1422042,'Jednorożec','przasnyski','mazowieckie','Urząd Gminy Jednorożec','www.jednorozec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (838,1420062,'Joniec','płoński','mazowieckie','Urząd Gminy Joniec','www.ugjoniec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (845,1415052,'Kadzidło','ostrołęcki','mazowieckie','Urząd Gminy Kadzidło','www.kadzidlo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (858,1432032,'Kampinos','warszawski zachodni','mazowieckie','Urząd Gminy Kampinos','www.kampinos.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (861,1411032,'Karniewo','makowski','mazowieckie','Urząd Gminy Karniewo','www.karniewo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (864,1436012,'Kazanów','zwoleński','mazowieckie','Urząd Gminy Kazanów','www.kazanow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (878,1434072,'Klembów','wołomiński','mazowieckie','Urząd Gminy Klembów','www.klembow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (887,1423032,'Klwów','przysuski','mazowieckie','Urząd Gminy Klwów','www.klwow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (913,1417052,'Kołbiel','otwocki','mazowieckie','Urząd Gminy Kołbiel','www.kolbiel.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (931,1426022,'Korczew','siedlecki','mazowieckie','Urząd Gminy Korczew','www.korczew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (935,1433032,'Korytnica','węgrowski','mazowieckie','Urząd Gminy Korytnica','www.korytnica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (948,1426032,'Kotuń','siedlecki','mazowieckie','Urząd Gminy Kotuń','www.kotun.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (950,1425072,'Kowala','radomski','mazowieckie','Urząd Gminy Kowala','www.kowala.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (960,1422052,'Krasne','przasnyski','mazowieckie','Urząd Gminy Krasne','www.krasne.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (963,1411042,'Krasnosielc','makowski','mazowieckie','Urząd Gminy Krasnosielc','www.gminakrasnosielc.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (988,1422062,'Krzynowłoga Mała','przasnyski','mazowieckie','Urząd Gminy Krzynowłoga Mała','www.krzynowlogamala.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (997,1437022,'Kuczbork-Osada','żuromiński','mazowieckie','Urząd Gminy Kuczbork-Osada','www.ugkuczbork.bip.org.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1012,1412102,'Latowicz','miński','mazowieckie','Urząd Gminy Latowicz','www.gmina-latowicz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1015,1415062,'Lelis','ostrołęcki','mazowieckie','Urząd Gminy Lelis','www.lelis.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1018,1414032,'Leoncin','nowodworski','mazowieckie','Urząd Gminy Leoncin','www.leoncin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1019,1432042,'Leszno','warszawski zachodni','mazowieckie','Urząd Gminy Leszno','www.gminaleszno.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1020,1418032,'Lesznowola','piaseczyński','mazowieckie','Urząd Gminy Lesznowola','www.lesznowola.waw.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1043,1413032,'Lipowiec Kościelny','mławski','mazowieckie','Urząd Gminy Lipowiec Kościelny','www.lipowieckoscielny.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1049,1433042,'Liw','węgrowski','mazowieckie','Urząd Gminy Liw','www.liw.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1067,1437032,'Lubowidz','żuromiński','mazowieckie','Urząd Gminy Lubowidz','www.uglubowidz.com');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1073,1437042,'Lutocin','żuromiński','mazowieckie','Urząd Gminy Lutocin','www.lutocin.i-gmina.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1090,1403062,'Łaskarzew','garwoliński','mazowieckie','Urząd Gminy Łaskarzew','www.laskarzew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1092,1419072,'Łąck','płocki','mazowieckie','Urząd Gminy Łąck','www.gminalack.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1118,1415072,'Łyse','ostrołęcki','mazowieckie','Urząd Gminy Łyse','www.gminalyse.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1121,1403072,'Maciejowice','garwoliński','mazowieckie','Urząd Gminy Maciejowice','www.maciejowice.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1122,1407062,'Magnuszew','kozienicki','mazowieckie','Urząd Gminy Magnuszew','www.magnuszew.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1129,1419082,'Mała Wieś','płocki','mazowieckie','Urząd Gminy Mała Wieś','www.malawies.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1131,1416052,'Małkinia Górna','ostrowski','mazowieckie','Urząd Gminy Małkinia Górna','www.malkiniagorna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1150,1403082,'Miastków Kościelny','garwoliński','mazowieckie','Urząd Gminy Miastków Kościelny','www.miastkowkoscielny.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1153,1421042,'Reguły','pruszkowski','mazowieckie','Urząd Gminy Michałowice','www.michalowice.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1158,1433062,'Miedzna','węgrowski','mazowieckie','Urząd Gminy Miedzna','gmina-miedzna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1181,1412112,'Mińsk Mazowiecki','miński','mazowieckie','Urząd Gminy Mińsk Mazowiecki','www.minskmazowiecki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1183,1430032,'Mirów Stary','szydłowiecki','mazowieckie','Urząd Gminy Mirów','www.mirow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1185,1428042,'Młodzieszyn','sochaczewski','mazowieckie','Urząd Gminy Młodzieszyn','www.mlodzieszyn.e-sochaczew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1186,1411052,'Młynarze','makowski','mazowieckie','Urząd Gminy Młynarze','mlynarze.bipgminy.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1189,1427032,'Mochowo','sierpecki','mazowieckie','Urząd Gminy Mochowo','www.mochowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1191,1426042,'Mokobody','siedlecki','mazowieckie','Urząd Gminy Mokobody','www.mokobody.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1208,1421052,'Nadarzyn','pruszkowski','mazowieckie','Urząd Gminy Nadarzyn','www.nadarzyn.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1212,1420072,'Naruszewo','płoński','mazowieckie','Urząd Gminy Naruszewo','www.naruszewo.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1226,1408032,'Nieporęt','legionowski','mazowieckie','Urząd Gminy Nieporęt','www.nieporet.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1233,1428052,'Nowa Sucha','sochaczewski','mazowieckie','Urząd Gminy Nowa Sucha','www.nowasucha.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1237,1420082,'Nowe Miasto','płoński','mazowieckie','Urząd Gminy Nowe Miasto','www.nowemiasto.win.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1247,1419092,'Nowy Duninów','płocki','mazowieckie','Urząd Gminy Nowy Duninów','www.nowyduninow.info.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1254,1416062,'Nur','ostrowski','mazowieckie','Urząd Gminy Nur','www.gminanur.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1258,1424022,'Obryte','pułtuski','mazowieckie','Urząd Gminy Obryte','www.obryte.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1262,1423042,'Odrzywół','przysuski','mazowieckie','Urząd Gminy Odrzywół','www.odrzywol.eu');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1263,1402062,'Ojrzeń','ciechanowski','mazowieckie','Urząd Gminy Ojrzeń','www.ojrzen.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1269,1410032,'Olszanka','łosicki','mazowieckie','Urząd Gminy Olszanka','www.olszanka.gminarp.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1271,1415092,'Olszewo-Borki','ostrołęcki','mazowieckie','Urząd Gminy Olszewo-Borki','www.olszewo-borki.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1278,1402072,'Opinogóra Górna','ciechanowski','mazowieckie','Urząd Gminy Opinogóra Górna','www.opinogora.home.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1284,1430042,'Orońsko','szydłowiecki','mazowieckie','Urząd Gminy Orońsko','www.oronsko.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1286,1417062,'Osieck','otwocki','mazowieckie','Urząd Gminy Osieck','www.osieck.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1303,1416072,'Ostrów Mazowiecka','ostrowski','mazowieckie','Urząd Gminy Ostrów Mazowiecka','www.gminaostrowmaz.home.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1313,1404032,'Pacyna','gostyniński','mazowieckie','Urząd Gminy Pacyna','www.pacyna.mazowsze.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1320,1426062,'Paprotnia','siedlecki','mazowieckie','Urząd Gminy Paprotnia','ppaprotnia.e-bip.pl/start/31');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1323,1403092,'Parysów','garwoliński','mazowieckie','Urząd Gminy Parysów','www.parysow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1347,1425082,'Pionki','radomski','mazowieckie','Urząd Gminy Pionki','www.gmina-pionki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1349,1410042,'Platerów','łosicki','mazowieckie','Urząd Gminy Platerów','www.platerow.com.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1353,1411062,'Płoniawy-Bramura','makowski','mazowieckie','Urząd Gminy Płoniawy-Bramura','www.ploniawy-bramura.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1354,1420092,'Płońsk','płoński','mazowieckie','Urząd Gminy Płońsk','www.ugplonsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1358,1406092,'Pniewy','grójecki','mazowieckie','Urząd Gminy Pniewy','www.pniewy.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1364,1424032,'Pokrzywnica','pułtuski','mazowieckie','Urząd Gminy Pokrzywnica','www.pokrzywnica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1366,1436022,'Policzna','zwoleński','mazowieckie','Urząd Gminy Policzna','www.policzna.ugm.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1370,1414052,'Pomiechówek','nowodworski','mazowieckie','Urząd Gminy Pomiechówek','www.pomiechowek.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1378,1434082,'Poświętne','wołomiński','mazowieckie','Urząd Gminy Poświętne','poswietne.bip-e.pl/portal/pos/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1383,1423052,'Potworów','przysuski','mazowieckie','Urząd Gminy Potworów','www.potworow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1386,1418052,'Prażmów','piaseczyński','mazowieckie','Urząd Gminy Prażmów','www.prazmow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1387,1401022,'Promna','białobrzeski','mazowieckie','Urząd Gminy Promna','www.promna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1391,1422072,'Przasnysz','przasnyski','mazowieckie','Urząd Gminy Przasnysz','www.przasnysz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1398,1426072,'Przesmyki','siedlecki','mazowieckie','Urząd Gminy Przesmyki','www.przesmyki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1406,1436032,'Przyłęk','zwoleński','mazowieckie','Urząd Gminy Przyłęk','www.przylek.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1411,1425092,'Przytyk','radomski','mazowieckie','Urząd Gminy Przytyk','www.przytyk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1421,1438032,'Puszcza Mariańska','żyrardowski','mazowieckie','Urząd Gminy Puszcza Mariańska','www.puszcza-marianska.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1425,1420102,'Raciąż','płoński','mazowieckie','Urząd Gminy Raciąż','www.gmina.raciaz.iap.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1441,1419102,'Radzanowo','płocki','mazowieckie','Urząd Gminy Radzanowo','www.radzanowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1442,1401032,'Radzanów','białobrzeski','mazowieckie','Urząd Gminy Radzanów','www.radzanow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1443,1413042,'Radzanów','mławski','mazowieckie','Urząd Gminy Radzanów','www.radzanow.com');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1445,1438042,'Radziejowice','żyrardowski','mazowieckie','Urząd Gminy Radziejowice','www.radziejowice.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1454,1421062,'Raszyn','pruszkowski','mazowieckie','Urząd Gminy Raszyn','www.raszyn.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1457,1402082,'Regimin','ciechanowski','mazowieckie','Urząd Gminy Regimin','www.regimin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1462,1429062,'Repki','sokołowski','mazowieckie','Urząd Gminy Repki','www.repki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1477,1427042,'Rościszewo','sierpecki','mazowieckie','Urząd Gminy Rościszewo','www.rosciszewo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1492,1423072,'Rusinów','przysuski','mazowieckie','Urząd Gminy Rusinów','www.rusinow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1496,1428062,'Rybno','sochaczewski','mazowieckie','Urząd Gminy Rybno','rybno.e-sochaczew.pl/media/index.php?MediumID=194');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1507,1435032,'Rząśnik','wyszkowski','mazowieckie','Urząd Gminy Rząśnik','www.rzasnik.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1509,1409042,'Rzeczniów','lipski','mazowieckie','Urząd Gminy Rzeczniów','www.rzeczniow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1511,1415102,'Rzekuń','ostrołęcki','mazowieckie','Urząd Gminy Rzekuń','www.rzekun.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1513,1411082,'Rzewnie','makowski','mazowieckie','Urząd Gminy Rzewnie','rzewnie.bipgminy.pl/public/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1516,1429072,'Sabnie','sokołowski','mazowieckie','Urząd Gminy Sabnie','www.sabnie.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1521,1433072,'Sadowne','węgrowski','mazowieckie','Urząd Gminy Sadowne','www.sadowne.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1523,1404042,'Sanniki','gostyniński','mazowieckie','Urząd Gminy Sanniki','www.sanniki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1526,1410052,'Sarnaki','łosicki','mazowieckie','Urząd Gminy Sarnaki','www.sarnaki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1536,1407072,'Sieciechów','kozienicki','mazowieckie','Urząd Gminy Sieciechów','www.sieciechow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1537,1426082,'Siedlce','siedlecki','mazowieckie','Urząd Gminy Siedlce','www.gminasiedlce.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1543,1437052,'Siemiątkowo','żuromiński','mazowieckie','Urząd Gminy Siemiątkowo','www.siemiatkowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1547,1412132,'Siennica','miński','mazowieckie','Urząd Gminy Siennica','www.ugsiennica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1549,1409052,'Sienno','lipski','mazowieckie','Urząd Gminy Sienno','www.sienno.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1555,1427052,'Sierpc','sierpecki','mazowieckie','Urząd Gminy Sierpc','www.gmina.sierpc.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1567,1426092,'Skórzec','siedlecki','mazowieckie','Urząd Gminy Skórzec','www.gminawskorcu.eu');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1578,1419112,'Słubice','płocki','mazowieckie','Urząd Gminy Słubice','www.slubice.org.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1583,1419122,'Słupno','płocki','mazowieckie','Urząd Gminy Słupno','www.slupno.eu');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1588,1417072,'Sobienie-Jeziory','otwocki','mazowieckie','Urząd Gminy Sobienie-Jeziory','www.sobieniejeziory.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1590,1403112,'Sobolew','garwoliński','mazowieckie','Urząd Gminy Sobolew','www.sobolew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1591,1428072,'Sochaczew','sochaczewski','mazowieckie','Urząd Gminy Sochaczew','www.gmina.e-sochaczew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1592,1420112,'Sochocin','płoński','mazowieckie','Urząd Gminy Sochocin','www.sochocin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1594,1429082,'Sokołów Podlaski','sokołowski','mazowieckie','Urząd Gminy Sokołów Podlaski','www.gminasokolowpodl.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1596,1409062,'Solec Nad Wisłą','lipski','mazowieckie','Urząd Gminy Solec Nad Wisłą','www.solec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1599,1435042,'Somianka','wyszkowski','mazowieckie','Urząd Gminy Somianka','www.somianka.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1601,1402092,'Sońsk','ciechanowski','mazowieckie','Urząd Gminy Sońsk','www.sonsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1612,1412142,'Stanisławów','miński','mazowieckie','Urząd Gminy Stanisławów','www.stanislawow.ug.gov.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1613,1419132,'Stara Biała','płocki','mazowieckie','Urząd Gminy Stara Biała','www.starabiala.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1614,1401042,'Stara Błotnica','białobrzeski','mazowieckie','Urząd Gminy Stara Błotnica','www.starablotnica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1618,1410062,'Stara Kornica','łosicki','mazowieckie','Urząd Gminy Stara Kornica','www.kornica.org');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1620,1432072,'Stare Babice','warszawski zachodni','mazowieckie','Urząd Gminy Stare Babice','www.stare-babice.waw.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1629,1419142,'Staroźreby','płocki','mazowieckie','Urząd Gminy Staroźreby','www.starozreby.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1633,1416082,'Stary Lubotyń','ostrowski','mazowieckie','Urząd Gminy Stary Lubotyń','www.lubotyn.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1638,1429092,'Sterdyń','sokołowski','mazowieckie','Urząd Gminy Sterdyń','www.sterdyn.nwg.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1641,1433082,'Stoczek','węgrowski','mazowieckie','Urząd Gminy Stoczek','www.stoczek.net.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1645,1434102,'Strachówka','wołomiński','mazowieckie','Urząd Gminy Strachówka','www.strachowka.com.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1647,1401052,'Stromiec','białobrzeski','mazowieckie','Urząd Gminy Stromiec','www.ugstromiec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1651,1413052,'Strzegowo','mławski','mazowieckie','Urząd Gminy Strzegowo','www.strzegowo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1658,1413062,'Stupsk','mławski','mazowieckie','Urząd Gminy Stupsk','www.stupsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1660,1426102,'Suchożebry','siedlecki','mazowieckie','Urząd Gminy Suchożebry','www.suchozebry.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1671,1411092,'Sypniewo','makowski','mazowieckie','Urząd Gminy Sypniewo','www.sypniewo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1675,1404052,'Szczawin Kościelny','gostyniński','mazowieckie','Urząd Gminy Szczawin Kościelny','www.szczawin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1679,1427062,'Szczutowo','sierpecki','mazowieckie','Urząd Gminy Szczutowo','www.szczutowo.nowybip.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1682,1411102,'Stary Szelków','makowski','mazowieckie','Urząd Gminy Szelków','www.szelkow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1685,1413072,'Szreńsk','mławski','mazowieckie','Urząd Gminy Szreńsk','www.szrensk.com.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1689,1416092,'Szulborze Wielkie','ostrowski','mazowieckie','Urząd Gminy Szulborze Wielkie','www.ugszulborze.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1691,1413082,'Szydłowo','mławski','mazowieckie','Urząd Gminy Szydłowo','szydlowo-maz.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1705,1424052,'Świercze','pułtuski','mazowieckie','Urząd Gminy Świercze','www.swiercze.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1725,1436042,'Tczów','zwoleński','mazowieckie','Urząd Gminy Tczów','www.tczow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1727,1428082,'Teresin','sochaczewski','mazowieckie','Urząd Gminy Teresin','www.teresin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1738,1403122,'Trojanów','garwoliński','mazowieckie','Urząd Gminy Trojanów','www.trojanow.pl/asp/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1739,1415112,'Troszyn','ostrołęcki','mazowieckie','Urząd Gminy Troszyn','www.troszyn.asi.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1784,1416043,'Brok','ostrowski','mazowieckie','Urząd Gminy w Broku','www.brok.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1789,1411073,'Różan','makowski','mazowieckie','Urząd Gminy w Różanie','www.rozan.eur.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1808,1416102,'Wąsewo','ostrowski','mazowieckie','Urząd Gminy Wąsewo','www.wasewo.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1814,1417082,'Wiązowna','otwocki','mazowieckie','Urząd Gminy Wiązowna','www.wiazowna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1819,1413092,'Wieczfnia Kościelna','mławski','mazowieckie','Urząd Gminy Wieczfnia Kościelna','www.bip.wieczfnia.akcessnet.net');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1824,1408052,'Wieliszew','legionowski','mazowieckie','Urząd Gminy Wieliszew','www.wieliszew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1830,1423082,'Wieniawa','przysuski','mazowieckie','Urząd Gminy Wieniawa','www.wieniawa.gmina.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1833,1425112,'Wierzbica','radomski','mazowieckie','Urząd Gminy Wierzbica','www.wierzbica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1835,1433092,'Wierzbno','węgrowski','mazowieckie','Urząd Gminy Wierzbno','www.wierzbno.bumsoft-2.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1844,1403132,'Wilga','garwoliński','mazowieckie','Urząd Gminy Wilga','www.ugwilga.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1849,1424062,'Winnica','pułtuski','mazowieckie','Urząd Gminy Winnica','www.gminawinnica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1851,1438052,'Wiskitki','żyrardowski','mazowieckie','Urząd Gminy Wiskitki','www.wiskitki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1855,1426112,'Wiśniew','siedlecki','mazowieckie','Urząd Gminy Wiśniew','www.wisniew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1856,1413102,'Wiśniewo','mławski','mazowieckie','Urząd Gminy Wiśniewo','www.wisniewo.bipgmina.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1868,1426122,'Wodynie','siedlecki','mazowieckie','Urząd Gminy Wodynie','www.wodynie.eu');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1880,1425122,'Wolanów','radomski','mazowieckie','Urząd Gminy Wolanów','www.wolanow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1893,1435062,'Zabrodzie','wyszkowski','mazowieckie','Urząd Gminy Zabrodzie','www.zabrodzie.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1897,1414063,'Zakroczym','nowodworski','mazowieckie','Urząd Gminy Zakroczym','www.zakroczym.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1899,1425132,'Zakrzew','radomski','mazowieckie','Urząd Gminy Zakrzew','www.zakrzew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1905,1420122,'Załuski','płoński','mazowieckie','Urząd Gminy Załuski','www.zaluski.iap.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1910,1416112,'Zaręby Kościelne','ostrowski','mazowieckie','Urząd Gminy Zaręby Kościelne','www.zareby-kosc.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1913,1424072,'Zatory','pułtuski','mazowieckie','Urząd Gminy Zatory','www.zatory.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1915,1427072,'Zawidz Kościelny','sierpecki','mazowieckie','Urząd Gminy Zawidz Kościelny','ug.zawidz.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1923,1426132,'Zbuczyn','siedlecki','mazowieckie','Urząd Gminy Zbuczyn','www.zbuczyn.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1939,1405062,'Żabia Wola','grodziski','mazowieckie','Urząd Gminy Żabia Wola','www.zabiawola.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1962,1400000,'Warszawa','warszawski','mazowieckie','Urząd Marszałkowski Województwa Mazowieckiego','www.mazovia.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1990,1402011,'Ciechanów','ciechanowski','mazowieckie','Urząd Miasta Ciechanów','www.umciechanow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (1999,1403011,'Garwolin','garwoliński','mazowieckie','Urząd Miasta Garwolin','www.garwolin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2003,1404011,'Gostynin','gostyniński','mazowieckie','Urząd Miasta Gostynin','www.gostynin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2009,1409033,'Lipsko','lipski','mazowieckie','Urząd Miasta i Gminy  Lipsko','www.lipsko.eu');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2011,1437013,'Bieżuń','żuromiński','mazowieckie','Urząd Miasta i Gminy Bieżuń','www.biezun.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2023,1419063,'Gąbin','płocki','mazowieckie','Urząd Miasta i Gminy Gąbin','www.gabin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2026,1418013,'Góra Kalwaria','piaseczyński','mazowieckie','Urząd Miasta i Gminy Góra Kalwaria','www.gorakalwaria.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2030,1412093,'Kałuszyn','miński','mazowieckie','Urząd Miasta i Gminy Kałuszyn','www.kaluszyn.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2033,1418023,'Konstancin-Jeziorna','piaseczyński','mazowieckie','Urząd Miasta i Gminy Konstancin-Jeziorna','www.konstancinjeziorna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2035,1429053,'Kosów Lacki','sokołowski','mazowieckie','Urząd Miasta i Gminy Kosów Lacki','www.kosowlacki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2048,1412123,'Mrozy','miński','mazowieckie','Urząd Miasta i Gminy Mrozy','www.mrozy.bip.net.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2057,1406083,'Nowe Miasto nad Pilicą','grójecki','mazowieckie','Urząd Miasta i Gminy Nowe Miasto nad Pilicą','www.nowemiasto.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2068,1418043,'Piaseczno','piaseczyński','mazowieckie','Urząd Miasta i Gminy Piaseczno','www.piaseczno.eu');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2069,1403103,'Pilawa','garwoliński','mazowieckie','Urząd Miasta i Gminy Pilawa','www.pilawa.com.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2078,1434093,'Radzymin','wołomiński','mazowieckie','Urząd Miasta i Gminy Radzymin','www.radzymin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2107,1401013,'Białobrzegi','białobrzeski','mazowieckie','Urząd Miasta i Gminy w Białobrzegach','www.bialobrzegi.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2112,1422023,'Chorzele','przasnyski','mazowieckie','Urząd Miasta i Gminy w Chorzelach','www.gminachorzele.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2117,1419053,'Drobin','płocki','mazowieckie','Urząd Miasta i Gminy w Drobinie','www.drobin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2131,1410023,'Łosice','łosicki','mazowieckie','Urząd Miasta i Gminy w Łosicach','www.losiceonline.republika.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2136,1406073,'Mogielnica','grójecki','mazowieckie','Urząd Miasta i Gminy w Mogielnicy','www.mogielnica.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2149,1408043,'Serock','legionowski','mazowieckie','Urząd Miasta i Gminy w Serocku','www.serock.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2151,1425103,'Skaryszew','radomski','mazowieckie','Urząd Miasta i Gminy w Skaryszewie','www.skaryszew.pl/index.php?option=18&action=articles_show&art_id=220');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2175,1403143,'Żelechów','garwoliński','mazowieckie','Urząd Miasta i Gminy Żelechów','www.zelechow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2186,1417011,'Józefów','otwocki','mazowieckie','Urząd Miasta Józefowa','www.jozefow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2196,1434011,'Kobyłka','wołomiński','mazowieckie','Urząd Miasta Kobyłka','www.kobylka.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2208,1408011,'Legionowo','legionowski','mazowieckie','Urząd Miasta Legionowo','www.legionowo.pl/pl/strona-glowna');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2222,1403021,'Łaskarzew','garwoliński','mazowieckie','Urząd Miasta Łaskarzew','www.miasto.laskarzew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2225,1434021,'Marki','wołomiński','mazowieckie','Urząd Miasta Marki','www.marki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2228,1405011,'Milanówek','grodziski','mazowieckie','Urząd Miasta Milanówka','www.milanowek.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2229,1412011,'Mińsk Mazowiecki','miński','mazowieckie','Urząd Miasta Mińsk Mazowiecki','www.minsk-maz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2230,1413011,'Mława','mławski','mazowieckie','Urząd Miasta Mława','www.mlawa.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2240,1461011,'Ostrołęka','Ostrołęka','mazowieckie','Urząd Miasta Ostrołęki','www.ostroleka.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2242,1416011,'Ostrów Mazowiecka','ostrowski','mazowieckie','Urząd Miasta Ostrów Mazowiecka','www.ostrowmaz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2244,1417021,'Otwock','otwocki','mazowieckie','Urząd Miasta Otwocka','www.otwock.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2249,1425011,'Pionki','radomski','mazowieckie','Urząd Miasta Pionki','www.pionki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2251,1462011,'Płock','Płock','mazowieckie','Urząd Miasta Płocka','www.ump.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2255,1422011,'Przasnysz','przasnyski','mazowieckie','Urząd Miasta Przasnysz','www.przasnysz.um.gov.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2277,1464011,'Siedlce','Siedlce','mazowieckie','Urząd Miasta Siedlce','www.siedlce.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2285,1428011,'Sochaczew','sochaczewski','mazowieckie','Urząd Miasta Sochaczew','www.sochaczew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2286,1429011,'Sokołów Podlaski','sokołowski','mazowieckie','Urząd Miasta Sokołów Podlaski','www.sokolowpodl.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2291,1465011,'Warszawa','warszawski','mazowieckie','Urząd Miasta Stołecznego Warszawy','www.um.warszawa.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2292,1412151,'Sulejówek','miński','mazowieckie','Urząd Miasta Sulejówek','www.sulejowek.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2328,1401063,'Wyśmierzyce','białobrzeski','mazowieckie','Urząd Miasta Wyśmierzyce','www.wysmierzyce.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2332,1434031,'Ząbki','wołomiński','mazowieckie','Urząd Miasta Ząbki','www.zabki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2337,1434041,'Zielonka','wołomiński','mazowieckie','Urząd Miasta Zielonka','www.zielonka.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2340,1438011,'Żyrardów','żyrardowski','mazowieckie','Urząd Miasta Żyrardowa','www.zyrardow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2395,1432013,'Błonie','warszawski zachodni','mazowieckie','Urząd Miejski w Błoniu','www.um.blonie.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2478,1405043,'Grodzisk Mazowiecki','grodziski','mazowieckie','Urząd Miejski w Grodzisku Mazowieckim','www.grodzisk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2484,1412073,'Halinów','miński','mazowieckie','Urząd Miejski w Halinowie','www.halinow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2486,1425033,'Iłża','radomski','mazowieckie','Urząd Miejski w Iłży','www.ilza.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2503,1417043,'Karczew','otwocki','mazowieckie','Urząd Miejski w Karczewie','www.karczew.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2530,1407053,'Kozienice','kozienicki','mazowieckie','Urząd Miejski w Kozienicach','www.kozienice.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2572,1433053,'Łochów','węgrowski','mazowieckie','Urząd Miejski w Łochowie','www.gminalochow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2573,1432053,'Łomianki','warszawski zachodni','mazowieckie','Urząd Miejski w Łomiankach','www.lomianki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2576,1411011,'Maków Mazowiecki','makowski','mazowieckie','Urząd Miejski w Makowie Mazowieckim','www.makowmazowiecki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2599,1438023,'Mszczonów','żyrardowski','mazowieckie','Urząd Miejski w Mszczonowie','www.mszczonow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2600,1415083,'Myszyniec','ostrołęcki','mazowieckie','Urząd Miejski w Myszyńcu','www.myszyniec.pl/');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2603,1414043,'Nasielsk','nowodworski','mazowieckie','Urząd Miejski w Nasielsku','www.nasielsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2613,1414011,'Nowy Dwór Mazowiecki','nowodworski','mazowieckie','Urząd Miejski w Nowym Dworze Mazowieckim','www.nowydwormaz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2636,1432063,'Ożarów Mazowiecki','warszawski zachodni','mazowieckie','Urząd Miejski w Ożarowie Mazowieckim','www.ozarow-mazowiecki.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2643,1421011,'Piastów','pruszkowski','mazowieckie','Urząd Miejski w Piastowie','www.piastow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2649,1420011,'Płońsk','płoński','mazowieckie','Urząd Miejski w Płońsku','www.plonsk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2652,1405021,'Podkowa Leśna','grodziski','mazowieckie','Urząd Miejski w Podkowie Leśnej','www.podkowalesna.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2664,1421021,'Pruszków','pruszkowski','mazowieckie','Urząd Miejski w Pruszkowie','www.miasto.pruszkow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2670,1424043,'Pułtusk','pułtuski','mazowieckie','Urząd Miejski w Pułtusku','www.pultusk.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2675,1420021,'Raciąż','płoński','mazowieckie','Urząd Miejski w Raciążu','www.miastoraciaz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2677,1463011,'Radom','Radom','mazowieckie','Urząd Miejski w Radomiu','www.radom.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2693,1427011,'Sierpc','sierpecki','mazowieckie','Urząd Miejski w Sierpcu','www.sierpc.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2738,1430053,'Szydłowiec','szydłowiecki','mazowieckie','Urząd Miejski w Szydłowcu','www.szydlowiec.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2746,1418063,'Tarczyn','piaseczyński','mazowieckie','Urząd Miejski w Tarczynie','www.tarczyn.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2750,1434113,'Tłuszcz','wołomiński','mazowieckie','Urząd Miejski w Tłuszczu','www.tluszcz.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2768,1406113,'Warka','grójecki','mazowieckie','Urząd Miejski w Warce','www.warka.org.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2773,1433011,'Węgrów','węgrowski','mazowieckie','Urząd Miejski w Węgrowie','www.wegrow.com.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2784,1434123,'Wołomin','wołomiński','mazowieckie','Urząd Miejski w Wołominie','www.um.wolomin.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2820,1435053,'Wyszków','wyszkowski','mazowieckie','Urząd Miejski Wyszków','www.wyszkow.pl');
INSERT INTO website (id, area_code, city, county, voivodeship, administrative_unit, url) VALUES (2822,1436053,'Zwoleń','zwoleński','mazowieckie','Urząd Miejski Zwoleń','www.zwolen.pl');